### ISSUE TITLE
Allow "order by last modified" in trainees page

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#1063]
Trainees page (https://amy.software-carpentry.org/workshops/trainees/) should allow "order by last modified" so that we can see records that have changed recently.

**Comment by chrismedrela** [comment]
Right now we don't have `Person.last_updated_at`, but this can be probably easily fixed by inheriting from `CreatedUpdatedMixin`.

**Comment by gvwilson** [comment]
:+1: for v1.10

**Comment by maneesha** [comment]
I'm closing this as I'm combining it with similar issues here #1512
