### ISSUE TITLE
Add detailed view for TrainingProgress

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#1084]

**Comment by gvwilson** [comment]
Can you please provide more details about this one?

**Comment by chrismedrela** [comment]
Now, we have only edit and delete views for TrainingProgress records. For consistency, we should add detailed view, so that TrainingProgress is first-class object.

**Comment by pbanaszkiewicz** [comment]
Ref #1085

**Comment by maneesha** [comment]
Closing this - I don't think there's anything we need to be able to see that we can't see.
