### ISSUE TITLE
Add a field for workshop type

### ISSUE THREAD

**Issue by tracykteal** [carpentries/amy#1087]
As we have more offerings of types of workshops, even within SWC and DC, it would be very useful to be able to track workshop type. We need this to track how often we're teaching certain materials for reporting and for maintenance. 

For Data Carpentry those would be things like Ecology-R, Ecology-Python, Genomics, Geospatial, etc.

SWC could have R, Python, MATLAB

Using this framework we could also add Library Carpentry workshops.

**Comment by pbanaszkiewicz** [comment]
Library Carpentry workshops should be tagged as `LC`, similarly to `SWC` and `DC`.

@maneesha @jduckles any thoughts about tracking "leading theme" of a workshop, as Tracy described?

**Comment by maneesha** [comment]
I think this is really important but I'd want to brainstorm with others how to do it.  

For example, someone might teach DC Ecology-R but also touch on Python.    Someone might teach SWC Python and also SQL.  Ideally I want to track how often our stardard lessons are taught, but also what kind of deviation there is from that.  

There's also the question of the overhead in actually recording this.  Can we add this to the workshop github page's metadata?  For example:




https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html
```
---
layout: workshop      # DON'T CHANGE THIS.
root: .               # DON'T CHANGE THIS EITHER.  (THANK YOU.)
carpentry: "FIXME"    # what kind of Carpentry (must be either "dc" or "swc")
# ....
etherpad:             # optional: URL for the workshop Etherpad if there is one
eventbrite:           # optional: alphanumeric key for Eventbrite registration, e.g., "1234567890AB" (if Eventbrite is being used)
lessons: ["FIXME]  # Select from: R, Python, SQL...
```

**Comment by jduckles** [comment]
I think we just need an enumeration of modules taught, not necessarily the "leading theme".

I submitted the mechanics for capturing the lessons being taught via yaml headers in `swcarpentry/bc` a long time ago. Back then it was rolled-back as "too complicated", and the primary goal was to have appropriate setup instructions on the page. 

I think we have two motivations for it now and it might be time to bring it back. I can also see how the `swcarpentry/workshop-template` in conjunction with the `swcarpentry/styles` (the lesson template) and the GitHub repo names using `orgname/reponame` would allow us to build workshops from all available lessons in the community that use the template.

If I were to bring it back I'd suggest we use the actual github repo slugs like: `["swcarpentry/shell-novice","swcarpentry/git-novice","swcarpentry/python-novice-inflamation"]`. Then we can allow even forked repos that are based on the underlying template.

History of my PR which was eventually rolled back:
Example of how it worked: https://github.com/swcarpentry/DEPRECATED-bc/pull/415/commits/92a4bc5cee099dca3ed37313c13be452ba1488b7#diff-eacf331f0ffc35d4b482f1d15a887d3bR16

Full PR here: https://github.com/swcarpentry/DEPRECATED-bc/pull/415

**Comment by jduckles** [comment]
Also see https://github.com/swcarpentry/workshop-template/pull/305 for a discussion of bringing back yaml logic for setup instructions.

**Comment by tracykteal** [comment]
In the Data Carpentry workshop template, we do have the 4 topics in the YAML header and they populate the schedule

https://github.com/datacarpentry/workshop-template/blob/gh-pages/index.html

I agree pulling the modules in from the workshop template makes a lot of sense.

I think we will also want to be able to note the overall type of workshop, e.g. Genomics Data Carpentry, Python Software Carpentry, R Ecology Data Carpentry, so maybe that could be in the YAML headers as well, but it also might want to be something we note at the time of the workshop request. So, I don't know if that would have to be handled differently.

**Comment by tracykteal** [comment]
@pbanaszkiewicz what's easiest to implement? Adding a field for 'type of workshop' or pulling in more info from the workshop website?

**Comment by maneesha** [comment]
I think we could add it to the workshop request form but not make it a mandatory field.  Or have an option saying "Unsure; please contact me."  Lots of people don't know what they want when they make the request and I often talk them through their options.

**Comment by wking** [comment]
@jduckles [wrote][1]:
> I think we just need an enumeration of modules taught, not necessarily the "leading theme".

Besides YAML headers, I've also tried to get this into something machine-readable with wking/swc-setup-installation-test#9.  But that's still floating, because I haven't been able to convince lesson maintainers (or third parties) to write the per-lesson `requirements.json`.

[1]: https://github.com/swcarpentry/amy/issues/1087#issuecomment-264555153

**Comment by maneesha** [comment]
We now have the ability to track when a workshop covers our standard curricula.  Our new workshop request form will also have a "mix and match" option, where people will have a free text field to note how they may have taught Carpentries curricula outside our standard offerings.  A future version of the project will consider how we can code these free text responses.
