### ISSUE TITLE
Make easy to match AMY and SurveyMonkey data

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/amy#1148]
At the moment is **very** difficult to match AMY and SurveyMonkey data to extract information **necessary** when pitching grants.

# User case

If we want for partners to renew their partnership we should help them to pitch grants where we are included and for that we need to provide some data about the workshops they organised such as

- number of workshops, 
- number of attendees,
- topics taught,
- reception/feedback from attendees, ...

# Expectations

Partners could email Software Carpentry or Data Carpentry and have in 48 hours a anonymize spreadsheet with the data of their workshops so they could do their own data analyse and an default data summary.

# Current State

Some data are on AMY (e.g. number of workshops and number of attendees) but other are on SurveyMonkey (e.g. topics taught and reception). Unfortunately, there is no "column" on the exported data provided by AMY and SurveyMonkey that could be used to match the information.

# Technical information

SurveyMonkey store a human readable "slang" for the workshop, e.g. "Host, Month Day1-Day2 Year".

![screenshot_2017-02-09_11-12-51](https://cloud.githubusercontent.com/assets/1506457/22781389/368dfeba-eeba-11e6-9e8a-1242b0f58cb1.png)

We don't have that information stored on AMY in one field although it can be compose using other fields and some "script magic".

# Proposal

Add to AMY a field called `survey_monkey_slang` to store the related "column" name on SurveyMonkey
and populate it from past workshops plus auto-populate for new workshops.

# Possible interested on this

- @apawlik
- @anenadic
- @simonhettrick

**Comment by maneesha** [comment]
Closing as we no longer have the big drop down menu in Survey Monkey and are also considering using Typeform instead of SM.
