### ISSUE TITLE
Community Roles: create single instructor badge

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/amy#1162]
The Trainer community and staff have decided to move to a single checkout procedure that qualifies the new instructor as both a Data and Software Carpentry instructor. We need to implement a new "instructor" badge and automatically give it to any existing person who has either a Data or Software carpentry instructor badge (or both).

**Comment by chrismedrela** [comment]
@ErinBecker so what are the requirements to become certified instructor? Is it still passing TTT training, homework, discussion session and demo session, just without any distinction between SWC and DC?

@maneesha there are two approaches:

- keep "SWC Instr." and "DC Instr." badges and add "Instructor" badge;
- reuse "SWC Instructor" and rename it to "Instructor", award it to all people who have "DC Instructor" badge and delete "DC Instructor" badge.

The last one is simpler to implement, but results in some information loss. Any opinions?

Note to person implementing it: this requires the following changes:

- [ ] add Instructor badge
- [ ] write migration that adds Instructor badge to all people who have SWC or DC Instructor badge 
- [ ] trainees list view: eligible column, change the algorithm compucing eligibility
- [ ] trainees list view: "is swc/dc instructor?" filter
- [ ] people list view: dc?, swc? columns
- [ ] changes to requirement types: add "Homework" and "Demo Session"
- [ ] find workshops stuff: instructor badges filter and column

And probably more changes.

**Comment by ErinBecker** [comment]
@chrismedrela Thanks for the speedy response! The second option (reuse SWC instructor and rename to Instructor) is my preference. 

The requirements are as you listed "passing TTT training, homework, discussion session and demo session, just without any distinction between SWC and DC?"

**Comment by pbanaszkiewicz** [comment]
@chrismedrela how big this change looks? Pretty-big, medium, small?

**Comment by chrismedrela** [comment]
@pbanaszkiewicz looks like small changes in a lot of places, so I'd say medium.

**Comment by maneesha** [comment]
@ErinBecker in the interest of data persistency I'd recommend creating a new badge rather than reusing SWC instructor.

**Comment by maneesha** [comment]
Also note that this will require changing the `Instructor training progress` to not have separate DC Demo, SWC Demo and DC homework, SWC homework.

**Comment by pbanaszkiewicz** [comment]
Ref #1232.

The instructor training progress requirements have been changed (#1226 and corresponding PR #1296).

**Comment by maneesha** [comment]
I know we've brought this up with our Trainers community, but I don't think we are ready to take action.  Is that right?  In that case I'd suggest option 3 for now.  Let me know what you think @karenword @ErinBecker 

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by karenword** [comment]
Yes we should address this but #3 for now.

**Comment by ErinBecker** [comment]
Agreed with Karen - 3. this will require some conversation with the community to make sure that we're going the right direction. For example, whether we're doing ONLY a single "The Carpentries" badge or if we're doing "The Carpentries" + optional lesson specific badges.

**Comment by maneesha** [comment]
This is something we've been talking about for a long time, but are not ready to take any action on.

**Comment by maneesha** [comment]
@pbanaszkiewicz Do you want to keep this open here (as it's being addressed in the community roles project)?

**Comment by pbanaszkiewicz** [comment]
@maneesha @fmichonneau I'd like to move this to Community Roles project, if you agree.

**Comment by maneesha** [comment]
OK by me but we should wait until after the new year for François to have time to respond.  We will also need to adjust the logic and options for awarding badges.
