### ISSUE TITLE
What needs to be documented?

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#1171]
@maneesha you mentioned that we need more documentation. What exactly should be documented? I'm enumerating some ideas below.

1. description of infrastructure (automatic backups, server configuration, Travis CI)
2. procedures for deployment, release; or restoring from a backup (we've never done it yet)
3. how to run AMY on your machine
4. how to contribute (quick start for new contributors)
5. AMY feature documentation
6. release notes
7. user manuals (how to use AMY as a user; podcasts could be a good format)
8. developer documentation: 
    1. directory hierarchy
    2. architecture (how AMY is split into multiple Django apps, what external APIs do we use etc.)
    3. description of models 
    4. API reference
    5. REST API reference
9. something related to PyData?
10. FAQ
11. Troubleshooting documentation

**Comment by maneesha** [comment]
All of the above.
(although I don't know anything about how this is used for PyData)

**Comment by chrismedrela** [comment]
@maneesha Sorry, I asked wrong question. What needs to be documented _in the first place_? What should we focus on?

**Comment by maneesha** [comment]
For all of you, I'd start with item 8 (developer documentation).  There's probably things in items 1-5 that are related to the developer documentation.  I believe that @pbanaszkiewicz  has been blogging release notes so we should have that already, correct? 

For item 7 (user manual), 10 (FAQ), and 11 (troubleshooting), I've already put together a lot of notes offline.  I can work on publishing these over the next few months.

**Comment by maneesha** [comment]
Closing this
Per @pbanaszkiewicz  developer documentation is complete [in the docs folder in this repo](https://github.com/carpentries/amy/tree/develop/docs).

End user documentation is complete in [The Carpentries Handbook](https://docs.carpentries.org/topic_folders/workshop_administration/amy_manual.html).
