### ISSUE TITLE
Define "Active" instructors

### ISSUE THREAD

**Issue by jduckles** [carpentries/amy#1209]
We define an active instructor as:

"Every qualified instructor who has taught at least twice in the past two calendar years (730 days prior to the announced election date)."

It would be nice to have an active/inactive flag in AMY.

It would also be nice to have a way to see a feed of recently (30/60/90/120 days) inactive members in order to contact them and remind them that they've lost voting eligibility. 

On the flip side, I would like to be able to welcome new instructors to "voting" status when they're listed in AMY as having taught twice.

**Comment by maneesha** [comment]
This:

> "Every qualified instructor who has taught at least twice in the past two calendar years (730 days prior to the announced election date)."

is actually how we define "member."

I don't think we've defined "active" in any way.  I don't want newly trained instructors who haven't taught yet, or have only taught 1x, to be considered inactive.  I'd see "members" as a subset of "active" instructors.

**Comment by maneesha** [comment]
Closing this as we don't have a definition for "active" and use Redash queries to get lists of qualifying voting members.
