### ISSUE TITLE
Instructor profile form missing DC/OpenRefine option

### ISSUE THREAD

**Issue by kariljordan** [carpentries/amy#1211]
On the instructor profile [form](https://amy.software-carpentry.org/forms/update_profile/) under "Topic and lessons you're comfortable teaching", OpenRefine is missing from the list. Also, @maneesha said, "I think this section needs work overall -- for example I don't think we need to be separating out dc/python and swc/python, etc."

**Comment by jduckles** [comment]
I just dug into this one looking at the AMY DB in a dev installation of AMY, it looks like we can add/edit the names of these in the table `workshops_lesson`.

That table currently contains:
```
sqlite> select * from workshops_lesson;
1|swc/git
2|swc/make
3|swc/matlab
4|swc/hg
5|swc/python
6|dc/python
7|swc/r
8|dc/r
9|swc/regexp
10|swc/sql
11|dc/sql
12|swc/svn
13|swc/shell
14|dc/shell
15|dc/spreadsheets
16|dc/cloud
```

To add new ones we need to increment the `id` and insert the new tag:
```
sqlite> insert into workshops_lesson values (17, "dc/geo");
```
If we combine `swc/python` and `dc/python` into just `python` we'll need to run an update query to move people from the old one to the new id. I haven't figured out where those records for each person live yet, but when we find them, it will be a relatively straight forward update query to walk them to the unified id.

@kariljordan and @maneesha can you please propose a new list for instructors to indicate their confidence in teaching and we can put a plan in place to roll them out.

**Comment by kariljordan** [comment]
The list of **topics** I propose is:

Git
Python
R
Shell
Spreadsheets
OpenRefine
SQL

I'm not sure how much we push MATLAB and Make. We should keep them on the list since we have lessons for them, right?

When instructors go through checkout they can technically teach all of our lessons. Do we need to ask them which lessons they're comfortable teaching, or can we just ask what topics?

@maneesha it would probably be good to keep collecting as much info as possible, right? Which topic **and** which lesson?

**Comment by maneesha** [comment]
Closing this here as it's being discussed in #1513
