### ISSUE TITLE
Find a way for Select2 to programmatically search

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1246]
With switch from django-selectable to django-autocomplete-light, a newer and better autocomplete widget was introduced: [Select2](https://select2.org/).

Unfortunately in about 5 places we used django-selectable to programmatically find something in and select from one of AMY's lookups (e.g. a language by it's subtag ('EN' for English, 'PL' for Polish, etc.).
This feature was dropped in #1245. If there's a way to bring it back, we should try.

**Comment by maneesha** [comment]
@pbanaszkiewicz  Can you share more information about what this means and how it will impact us?

**Comment by pbanaszkiewicz** [comment]
@maneesha this was mostly for me; in some places we use [Select2](https://select2.org/) widgets. I want to be able to load data asynchronously into such widget and then programmatically (via JavaScript) select specific item from the list. Unfortunately it seems Select2 [dropped such feature](https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2).

**Comment by fmichonneau** [comment]
If I understand your last comment correctly:

> Unfortunately it seems Select2 dropped such feature.

Should we keep this issue open?

**Comment by pbanaszkiewicz** [comment]
Let's close it. We can always reopen when this feature becomes important.
