### ISSUE TITLE
Question: should we semi-automate "Remove requests"?

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1249]
To comply with GDPR we must respect users' right to request removal of their data from the AMY database. No-automated way would be an email endpoint for them to contact, and a person would then verify the request and proceed with manual removal of the data.

Semi-automated way would work just like event requests: an admins with privileges would go through requests, verify them and finally push "Confirm removal of users data" button that does all the magic.

Pinging @jduckles  for comments.

**Comment by jduckles** [comment]
Yes, we cover this in the updated privacy policy language. Lets start with the non-automated way and then consider scoping out the automated way later.

**Comment by pbanaszkiewicz** [comment]
Soooo... defer for now and implement in maybe v1.12 or so?

**Comment by jduckles** [comment]
Yep, our policy language covers this, we can at least sketch out the drop queries necessary to remove someone's identity. An interesting question is if it will be ok to just randomize/anonymize their personal information and leave the rest of their record intact. It gets really interesting when you've aggregated an individual's information into an annual report say, and they say they want their data removed and you've already counted them. How do you, can you even, un-count them when they exercise their right to be forgotten.

**Comment by pbanaszkiewicz** [comment]
@jduckles to my understanding, as long as reports don't use personally identifiable information, we shouldn't need to remove person's data from them.

I am, however, interested to see if we need to remove IP address from server logs when someone invokes their right to be forgotten.

**Comment by jduckles** [comment]
We're teetering on the edge of existential philosophy here 😆

**Comment by maneesha** [comment]
As this has to do with law compliance, I am deferring to @tracykteal and @elizabethwilliams8 on this.

**Comment by maneesha** [comment]
Is this covered through the work @lauryndbrown  is doing with @fmichonneau ?

**Comment by maneesha** [comment]
@fmichonneau  is this covered through the new consent work we've done?

**Comment by fmichonneau** [comment]
yes, we now have the option to "Archive" a profile.
