### ISSUE TITLE
Migrate repo to github.com/carpentries

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/amy#1312]
AMY is part of The Carpentries infrastructure and this repository should move to https://github.com/carpentries/amy. This migration should create any problems.

@jduckles or @fmichonneau Could you migrate this repo, please?

**Comment by jduckles** [comment]
I don't want to migrate this repo until the current development surge settles down. It is actively being hit by @pbanaszkiewicz these days. AMY will be moving to new servers in a couple of months and we can rip out the carpet from underneath everything all at once then.

**Comment by maneesha** [comment]
Now that AMY is hosted at  https://amy.carpentries.org/ can we move the repo to the `carpentries` organization?  What do we need to do to make this happen?

**Comment by fmichonneau** [comment]
I can transfer the repo. @pbanaszkiewicz is there any integrations or other things that could be affected by migrating the repo?

**Comment by pbanaszkiewicz** [comment]
@fmichonneau probably only Travis-CI. But once that's broken we can probably fix it easily.

If you can, please look for something like this: https://github.com/settings/tokens but for AMY / swcarpentry organization. I have the GitHub API token saved somewhere but I'm unsure if we're using it and where it came from.

**Comment by fmichonneau** [comment]
I don't see any AMY-specific tokens. 
The project has now been transferred to carpentries organization.
Please report any issues following the transfer.
