### ISSUE TITLE
add new badges for curriculum specific onboardings

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/amy#1338]
We are about to start running onboarding sessions to train already certified Carpentry Instructors for teaching newly developed curricula. The first curriculum to test this process will be Geospatial. Onboarding for Geospatial lessons starts September 17th.

Ideally, after an Instructor completes the onboarding, I would like to give them a badge showing that they are qualified to teach the Geospatial lessons (new badge = "Geospatial Instructor"). I recognize that this probably won't be implemented before the first onboarding on the 17th, so as a backup plan, I can create a new event in AMY to store information about who attends the onboarding sessions. I can then award badges based on attendance once the badge exists.

We will also be running Genomics onboarding and Social Sciences onboarding within the next quarter, so it would be good to start now by creating the following badges:

- "Geospatial Instructor"
- "Social Sciences Instructor"
- "Genomics Instructor"

These badges will be used by @sheraaron and @maneesha  when assigning Instructors to teach new curricula. 

Please let me know if you need any more information before this can be implemented. Thanks!

**Comment by ErinBecker** [comment]
When assigning Instructors to workshops, priority will be given to people who have been badged for that curriculum. People need to go through the onboarding (but they can sign up for the workshop before they’ve done that and go through onboarding in the meantime). For pilots and self-organized workshops, anyone can teach the curriculum, no lesson-specific badging needed. @maneesha @sheraaron

**Comment by maneesha** [comment]
I'd like to give this more thought to think about what else we need to do to implement it.  For example none of these badges should be allowed unless the person already has a SWC or DC instructor badge.

**Comment by maneesha** [comment]
Thanks @ErinBecker  To be clear then, people who have not gone through instructor training (and therefore may not know about our pedagogical practices, our operations, etc.) may be eligible for the curriculum-specific badge and can then teach these workshops (but no other workshops)?  

If they have applied for instructor training but have not attended, we don't know anything about them, especially if the application has not been reviewed.

**Comment by ErinBecker** [comment]
@maneesha - They would not be qualified to start teaching until they also completed the instructor training. If someone chose to complete onboarding before doing their Instructor Training, this badge would be a placeholder only. Once they completed their Instructor Training and certification, they would then be qualified to teach SWC and DC workshops and would have priority for the specific lesson they're badged on.

**Comment by sheraaron** [comment]
@ErinBecker  and @maneesha  what would the workflow look like for the badging. I'd like to be clear how I would know when I am triggered to apply this badge. ie,  the learners go through onboarding and then a message is sent to Checkout@carpentries for me to go and badge them? Who is conducting on the onboarding, will it always be @ErinBecker ? Can we be sure to add to the workflow and let me know the process letting me know when I am to apply the badge?

**Comment by maneesha** [comment]
Yes, @ErinBecker , as @sheraaron  noted above a clear workflow would be useful.  
I was confused about Erin's statement above:

> [...] for people who have attended Instructor Training (but not finished checkout) or who have applied for training (but not yet attended), 

and then

> They would not be qualified to start teaching until they also completed the instructor training. [...]
 Once they completed their Instructor Training and certification, they would then be qualified to teach SWC and DC workshops and would have priority for the specific lesson they're badged on.

When someone applies, we don't know when their application will be reviewed, and then if they are invited to join a training, when their schedule permits to join one.  So they could end up with this placeholder badge for quite some time.  Or it could be that they apply, they are *not* accepted/invited to an event, and so they get this curriculum badge even though they will not be invited to join a training event in the near future.

So they still need the SWC or DC instructor badge to teach; this proposal is a way to identify people who have the curriculum specific experience, correct?

And  the curriculum specific badge is giving people priority to teach these workshops, correct? Or is it a requirement to teach these workshops?

**Comment by pbanaszkiewicz** [comment]
Hello all,

> Yes, @ErinBecker , as @sheraaron noted above a clear workflow would be useful.

I second that, for example it was very helpful for me to follow [the draft](https://github.com/swcarpentry/amy/issues/1055#issuecomment-416948374) for #1055.

My other input is that badges are essentially awards, and are used to determine person's status. What you're talking about is... I don't know, it feels more like an achievement or supplementary training. It belongs more to the curriculum of the lessons. Personally I'd keep it separate from badges.

**Comment by ErinBecker** [comment]
Thanks for the discussion everyone! We've now discussed this issue at both the Instructor Training Team and the Curriculum Team meetings. The consensus is that we do want to have these as badges, as these will be "awards used to determine a person's status". For the short term, that status is "priority placement for centrally-organized workshops teaching this curriculum". In the long term, we are planning to move towards curriculum-specific badges being required (not just giving priority) for teaching a specific workshop. 

The workflow will be:

1. A person who is interested in teaching a specific curriculum either:
a) attends an onboarding session (these will be hosted by me to start and later hosted by others I've trained to run them) OR
b) watches a recording of an onboarding session
(both of these options will be available)

2) a) The host of the onboarding session sends an email to checkout@carpentries.org with a list of all those who have attended the session OR 
b) The person who watched the recorded onboarding sends an email to checkout@carpentries.org notifying us that they watched it (there may be some other information they need to include in the email in order to confirm that they've watched the video - I'm thinking of how to do this)

3) The person in charge of checkout@ (currently @sheraaron) awards each of these people the appropriate badge in AMY.

4) When listing workshops that are looking for Instructors, @sheraaron and the other workshop admins add a column/field to the signup sheet asking if the person signing up has completed onboarding (and provides a link to the onboarding video). 

5) When selecting Instructors for workshops, @sheraaron and the other workshop admins prioritize Instructors who answered "Yes" in the signup sheet to the question about whether they have done onboarding (the admins will also confirm this information by looking in AMY).*

* I don't know how many people usually sign up to teach a workshop. If there are only a handful, it might not be too difficult for the admins to look at each person in AMY and see whether they have the onboarding badge, but if there are a lot of people I can see this getting onerous. With the system described above, they could do initial workshop assignments just by looking at the signup sheet and then confirm in AMY before sending out emails to the selected Instructors. 

We also discussed at the team meetings what the title of the badge should be (some don't like "Instructor" being in the name as it implies that the person has also certified as an Instructor). There are a few different suggestions. I'll finalize this discussion with the staff and will update this issue once a consensus is reached.

**Comment by maneesha** [comment]
I'm trying to categorize things to develop a timeline for working on AMY.  I think this is an option 3 issue (esp. based on my comments in #1513) --  but please let me know if you have other thoughts @ErinBecker  @sheraaronhurt 

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by ErinBecker** [comment]
5. We can close this issue as we have been tracking onboarded instructors through events, rather than badges.
