### ISSUE TITLE
Remove NA option for workshop fee

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1403]
* "Not applicable" should not be an option.

![image](https://user-images.githubusercontent.com/829690/48513409-b4d59700-e829-11e8-89ff-d4c7f705b919.png)

**Comment by pbanaszkiewicz** [comment]
My guess as to why "Not applicable" is doing here: admin fee question is specific only to "Centrally-organized" workshop type. There needs to be something selected in admin fee question, so in case user is requesting a "Self-organized" question they need to select "admin fee"; by default that selection was "Not applicable".

If I remove "Not applicable", I'll have to select another option as default. Which one should that be? The very first one ("Im with a government site...")?

**Comment by maneesha** [comment]
Does an option need to be selected on form load?  We do require that the user select one option.

**Comment by pbanaszkiewicz** [comment]
I looked into "admin fee" field more and it turns out it can be left with no default selection. I'm working on a fix.
