### ISSUE TITLE
Country list for SurveyMonkey missing UK and Ireland

### ISSUE THREAD

**Issue by peterjc** [carpentries/amy#1415]
I hope this is the appropriate place to log this issue - I couldn't find anything directly about the SurveyMonkey in the code but several issues talked about integrating it.

I noticed this when reviewing the results for https://starescomp.github.io/2018-11-27-standrews/ - but it applies to other (recent) workshops too, e.g. http://sbc.shef.ac.uk/2018-11-26-sheffield/ where I checked the "Pre-workshop Survey" and "Post-workshop Survey" (but did not submit a full result, aborting after reaching the country question).

The drop down is missing the _Republic of Ireland_, and has _Great Britain_ rather than _United Kingdom_ (and thus is missing _Northern Ireland_ too).

<img width="648" alt="screenshot 2018-11-26 14 48 06" src="https://user-images.githubusercontent.com/63959/49021915-99547f80-f18b-11e8-9a1b-8171d9322f9d.png">

I think this listing and keyboard entry of U and K likely explains two mis-entered countries of _Korea, democratic republic of (South Korea)_ (which confusingly to me is sorted under S), and _Virgin Islands (UK)_ (the only appearance of the abbreviation "UK") while most of the group picked _Great Britain_.

Expected Results:

Add: "Ireland"
Replace "Great Britain" with "United Kingdom (UK)"

**Comment by peterjc** [comment]
Thanks - for future reference was there a better place to log this issue?

**Comment by kariljordan** [comment]
@peterjc logging it here was a great idea. Thank you so much.

**Comment by maneesha** [comment]
@kariljordan  Can I close this here now? Are you tracking this anywhere else?

**Comment by kariljordan** [comment]
Now that we are moving to Typeform, we need to see if @fmichonneau has changed this.

**Comment by fmichonneau** [comment]
I'm keeping track of this in asana as it's not related to AMY. Thanks!
