### ISSUE TITLE
Instructor Training Application checkbox to opt-in for Open review process

### ISSUE THREAD

**Issue by karenword** [carpentries/amy#1501]
This is not urgent, but if it is a quick fix, it would be a fantastic improvement.

Currently, applications are routed to our Open Instructor Training program when they are missing a Registration Code. This means that anyone who forgets to enter a code ends up taking time for unnecessary application review.

It would be much more straightforward to have a checkbox with text like this: "OPEN INSTRUCTOR TRAINING APPLICANTS: Check here if you would like this application to be reviewed for admission to our Open Instructor Training program. If you have already been invited to attend a training, please do not select this box."

**Comment by maneesha** [comment]
Thanks @karenword.  This sounds like a good idea.
I'll discuss this with @pbanaszkiewicz  in our upcoming workflows.

**Comment by pbanaszkiewicz** [comment]
We already have some features implemented for v2.8, but I can try to squeeze this into `master` some other way than before and therefore make a v2.7.1 release.

**Comment by maneesha** [comment]
Thanks @karenword 
To be clear, would we also want them to use the Group Code box for anything?  We can still leave it as is otherwise.  Should we have some information about what "Open Instructor Training" means?  Perhaps to say *not* to check this box if they are with a member site?

What if we had two options:

1. If you are joining with a member site, please enter your registration code or member site name here.
2. If you are not affiliated with a member site and are applying through our open application program, check this box.

And then we'd want validation to be sure they didn't do both.

**Comment by maneesha** [comment]
@karenword  I'm assuming your answer will be 1, but please let me know:  


**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by karenword** [comment]
Definitely #1! :) I like the options. Maybe this should be a drop-down choice so that they are mutually exclusive? Options could be: 'Member Affiliate (pre-approved for training)' vs 'Open Applicant (submit application for review to receive an Open Instructor Training scholarship)' -- pinging @elizabethwilliams8 for thoughts on my use of "scholarship" here. Then the "Registration Code" field could be identified as "Member Affiliates only:  please enter your Registration Code here."

**Comment by elizabethwilliams8** [comment]
@karenword I like it. There may be a better word than scholarship in the future, but this is consistent with what we have been saying so far.

**Comment by maneesha** [comment]
I like this idea - that they choose "member" or "open" (and we can fine tune the language used here) and then if member they get a box to put in a code; if open they don't have that box.

**Comment by maneesha** [comment]
@pbanaszkiewicz  says:

> Changing the form to behave like this is tricky and may cause unpredictible challenges

Piotr, could you clarify what might happen? Are there other ways we could distinguish between open and member applications without relying on whether the group code is blank?

**Comment by pbanaszkiewicz** [comment]
@maneesha: sorry for not being clear. What I meant about changing the form and unpredictable challenges is that adjusting the HTML in the form may require some tricks / hacks / special JavaScript. I don't know upfront what that may be, but it could affect how long does the issue take to implement. The bottom line is that I'm sure I can change the form for you, just the time may vary.

**Comment by karenword** [comment]
@pbanaszkiewicz is this unpredictability specific to adding a checkbox or dropdown choice alone, or is it related to @maneesha 's  proposal that the registration code box appearance should depend on the checkbox being checked? The latter feature seems less important to me than having the checkbox/dropdown itself.

**Comment by elizabethwilliams8** [comment]
@karenword and @maneesha Upon reading the options for the check-boxes again, I think we should make the current 'Member (pre-approved for training)' a bit more broad and intuitive. What about 'Pre-Approved Group Registration (through Membership or other agreement with The Carpentries)' and ' Individual Open Training Application (submit application for review to receive a scholarship for Instructor Training through our Open Application Program)'. 

My thinking here is that we have groups that are not members (i.e. the DOE) who have instructor training seats through a contract and we have the waived instructor trainings through the scholarship program and the a la carte training form. In both of these cases, as well as Membership, a registration code should have been provided. And, if there are other things in the future, this covers them too! 

I would love to hear your thoughts on the wording for the Open Training Applications, Karen. My thinking is that using the word 'Individual' will clue people in memberships that they are part of a group and need that code (if it hasn't been given to them), and empower individuals thinking about applying for training and not sure if it is for them to make the decision alone.

**Comment by maneesha** [comment]
I think I like this option - to select one of the following as a radio button, with the option to enter a code if they are coming through a membership or agreement:

- Pre-Approved Group Registration (through Membership or other agreement with The Carpentries).  Please enter the code you were given here: 
- Individual Open Training Application (submit application for review to receive a scholarship for Instructor Training through our Open Application Program)

**Comment by maneesha** [comment]
@pbanaszkiewicz  Just tagging you to note a small change in the text for the question above (remove the word "Group").
