### ISSUE TITLE
Upgrade Django to v2.2+

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1504]

**Comment by maneesha** [comment]
@pbanaszkiewicz Can you share some information about why we need to make this upgrade and how it will impact us?

**Comment by pbanaszkiewicz** [comment]
@maneesha we currently use Django v1.7. Between v1.7 and current v2.2.3 there were two security releases. Although they were fixing bugs in a small component I don't think we use, we should upgrade to keep up with the changes in Django.

This upgrade shouldn't have any impact on users of AMY, it's maintenance.
