### ISSUE TITLE
Add +1 to Instructor Training auto-score for Chemistry

### ISSUE THREAD

**Issue by karenword** [carpentries/amy#1505]
If "areas of expertise" includes "Chemistry" Instructor Training applicants should now receive a +1 on their application auto-score.

**Comment by maneesha** [comment]
@karenword  Is this still relevant?  If so, do you see this as a one time change, or will we change how autoscoring works on a regular basis, depending on the communities we want to engage?  

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)  *I would think it would be this option if it's a one time change*
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning  *I would think it would be this option if we see the need to make changes to autoscoring regularly*
4. Not sure
5. No longer relevant - OK to close

An answer of 1 for now and 3 long term is also perfectly acceptable!

**Comment by karenword** [comment]
I believe this is still relevant and will continue to see changes regularly (hence option 3) but tagging @ErinBecker because I submitted this PR at her request.

**Comment by ErinBecker** [comment]
1. We have a grant obligation to build a community in Chemistry. There may be changes to this scoring in the future, but at the scale of 6mo-1yr, so I'd rather make this as a "one time" change and not worry about a general solution right now.
