### ISSUE TITLE
Default value for lesson publication consent

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1508]
Currently, the default value for the lesson publication consent is "No" making it impossible to distinguish between people who have not set the option yet, and people who have explicitly set it to "No".

* is there something we can currently do to try to distinguish between these 2 situations?
* could we add another option (e.g., "not set") that would become the default?

_____
Thank you for submitting this issue to AMY.  If this represents an urgent problem such as AMY not loading at all, please contact team@carpentries.org so we can respond promptly.

Non-urgent issues will be reviewed weekly by @maneesha.  She will follow up here with you and/or other team members if more information is needed. Issues will be prioritized, considering whether they identify broken features, identify potential enhancements to existing features, or request implemention of entirely new features.

After prioritizing, one of the following will happen:

* High priority issues will be included in an upcoming work cycle and labeled for an existing milestone.
* Medium to low priority issues will be considered for a future work cycle and labeled "later."  These will be re-reviewed periodically to consider them for an upcoming work cycle. 
* Issues that are stale, redundant, or are otherwise assessed not to positively impact user workflows will be closed and labeled "wont-fix"

Comments in the issue itself will provide further context. Please contact team@carpentries.org with any questions.  Thank you again for your contribution and helping us improve AMY.

**Comment by maneesha** [comment]
We could add an option for "unknown" and set that as default or make the default value be `null`.  @pbanaszkiewicz  What would make more sense to you?

**Comment by pbanaszkiewicz** [comment]
@maneesha I'll have to test which option is most suitable. Unfortunately I don't think there's a way to change "No" -> "Unknown" for people already in the database...

**Comment by fmichonneau** [comment]
@pbanaszkiewicz it looks like the history of the edits made to a profile is stored in the database. Could we query the history to know if someone has edited their own profile since the option has been introduced? it wouldn't be perfect as some people might have not seen the option but it could be an appropriate approximation.
