### ISSUE TITLE
Count of workshops is incorrect

### ISSUE THREAD

**Issue by jduckles** [carpentries/amy#1510]
Count of workshops is incorrect and seems to be about 10x what I'd expect the count to be:
![image](https://user-images.githubusercontent.com/119403/59891816-c10e7c00-942a-11e9-9e89-d2d96302f118.png)

https://amy.carpentries.org/reports/workshops_over_time/

**Comment by maneesha** [comment]
@pbanaszkiewicz In addition to this problem, I see some other problems with our reports.   For example,  [Learners over time](https://amy.carpentries.org/reports/learners_over_time/) does not load, and the API link returns a 500 error.  Some API links include `unset-variable` in the URL.  Did some of the queries or underlying data structures recently change?

**Comment by pbanaszkiewicz** [comment]
@maneesha @jduckles this is clearly a bug, I need to dive more to see where's the problem. Please let me know if this has high priority.

**Comment by maneesha** [comment]
Closing this as we no longer have reports inside AMY
