### ISSUE TITLE
Login screen should make admin/instructor log in different

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1517]
On the login screen, it makes it look like anyone can sign in with any account.  Because we want instructors to sign in via GitHub, we should make it clear that the username/password login is for Carpentries administrators only.

**Comment by fmichonneau** [comment]
I think anyone can log in using an AMY account and not necessarily use GitHub. Are we sure we can rely on all instructors having a GitHub account?

**Comment by maneesha** [comment]
From the technical perspective, yes, anyone can have a username/password.  However  we have been having instructors log in via GH only because we don't have the staff capacity to manage setting up individual logins for instructors.  We haven't had an issue with instructors not having GH accounts but can revisit this if it comes up.

**Comment by fmichonneau** [comment]
I see. Thank you for the clarification!
