### ISSUE TITLE
Attendance is calculated, not store in db?

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1519]
Looking at https://github.com/carpentries/amy/issues/1177, is it right that attendance is now not being stored in the database but rather being calculated in the app?  I hadn't considered this when we discussed that issue, and am now seeing a potential problem.  We  run SQL queries in redash for a lot of our data needs. Since the database only has a "manual_attendance" column, we aren't getting the calculated attendance result.

**Comment by pbanaszkiewicz** [comment]
Yes, attendance is calculated, not stored in DB. Only manual attendance is stored.

**Comment by maneesha** [comment]
Closing this as there is nothing specifically to do about this - just something we will need to be aware of when we run attendance reports externally.  Also @sheraaronhurt  has said we are no longer requesting attendance data so this is not a priority.
