### ISSUE TITLE
Login redirects from /trainee/autoupdate_profile back to /trainee

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries/amy#1520]
When visiting https://amy.carpentries.org/account/login/?next=/dashboard/trainee/autoupdate_profile/ and logging in (through GitHub in my case), I get redirected to [/trainee](https://amy.carpentries.org/dashboard/trainee/). However, because `?next=.../autoupdate_profile` is specified in the initial link, expected behaviour is  to land there.

**Comment by maneesha** [comment]
This may have other behaviors set that override what's in the initial link. For example when I log in (as an admin user) via the login link @katrinleinweber  shared above, I get redirected to the admin dashboard.  We'll consider looking into this but  as it's not really breaking any functionality, it probably won't be a high priority.

@katrinleinweber Is the login link one you've found shared somewhere (like one of our webpages)?  If so we can remove the `next` parameter to avoid this confusion.

**Comment by katrinleinweber** [comment]
I bookmarked the page where I can actually edit (`.../autoupdate_profile/`) in order to get there directly or with at max. only the login in between.

Indeed, it's not a high-prio bug, but the current redirection behaviour breaks the functionality "user lands where they specified".

**Comment by pbanaszkiewicz** [comment]
Can't reproduce, perhaps it was fixed at some point.
