### ISSUE TITLE
"Results could not be loaded" when trying to assign admin to event or request

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1538]
When trying to assign an admin to an event, the drop down does not load, and instead it says "The results could not be loaded"

This happens inconsistently.  Trying again will sometimes make the drop down list load.

![image](https://user-images.githubusercontent.com/829690/65254768-ce3f1380-daca-11e9-93f9-2067326b42f3.png)

**Comment by pbanaszkiewicz** [comment]
Does this only happen to assign admin window?

**Comment by maneesha** [comment]
Looks like this is happening in other views where you try to look up a name.  For example, assigning admin on the event view itself:

![image](https://user-images.githubusercontent.com/829690/65328417-474e7180-db84-11e9-8078-e9baf34a36cd.png)

And assigning tasks in an event:

![image](https://user-images.githubusercontent.com/829690/65328356-24bc5880-db84-11e9-9521-a1a1bba5f8c9.png)

**Comment by maneesha** [comment]
Comments from @Talishask  

AMY issue tied to the latest update - Hey @maneesha, I have been experiencing issues with name recognition when adding information into AMY. This issue seems to be pretty inconsistent in what it looks like, however this does have a significant impact on my ability to enter workshops. I have mainly been observing:
- it is is taking AMY longer than usual to pull up matches
- sometimes it doesn't pull up anything at all when I know there is a match in the system.
- Once you backspace in the input field it has an even more difficult time matching.
- There is a weird phenomenon when the matching works great just as it did before however only on even characters. So, if for example I am trying to pull up 'Talisha Sutton-Kennedy" the field would only show matches on the bolded characters(spaces included): T **a** l **i** s **h** a **_** S **u** t **t** o **n** - **K** e **n** n **e** d **y**

**Comment by pbanaszkiewicz** [comment]
For now it looks like the erratic behavior came from django-select2 using cache database that we didn't explicitly created.

For tests I added such cache table on production server (that's only place where the error would occur) and it seems fine now. I'm waiting for more tests from @Talishask and @maneesha.

**Comment by Talishask** [comment]
This issue appears to be resolved on my end.
