### ISSUE TITLE
Provide more control for visibility of curricula

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1557]
currently, curricula added through the Django admin interface get added in the workshop request forms. However, as we develop new lessons, they need to be piloted before they can officially be requested by anyone. In this transition period, instructors who want to self-organize a workshop can, however, do so.

A possible approach to this would be to create a new field associated with curricula (e.g., `visibility`) that could take the values:
- `private`: only visible within the logged in AMY interface
- `beta`: visible within the logged in AMY interface and in the self-reported workshops
- `public`: visible anywhere in AMY

A pitfall of this approach is that people who wanted to specifically run a pilot and used the workshop request form would still need to use a workaround (like selecting mix and match, writing in the comments the pilot they wanted to run, and edit the request afterwards to match the actual workshop they'd like to run).

@maneesha @sheraaronhurt @ErinBecker if you have more feedback or ideas on how to implement this, please let us know.

**Comment by maneesha** [comment]
@fmichonneau  Are you thinking about the whole workshop curriculum (i.e., "Data Carpentry: Ecology/Python") or the specific lessons within the workshop curriculum (Spreadsheets, SQL, OpenRefine, Python, R, etc.)?

**Comment by fmichonneau** [comment]
The whole workshop curriculum

**Comment by maneesha** [comment]
Tagging our curriculum team @tobyhodges @ErinBecker @fmichonneau @zkamvar  
This is a few years old. Is this still relevant?

**Comment by maneesha** [comment]
Can this be resolved with #2027?

**Comment by fmichonneau** [comment]
yes superseeded by #2027
