### ISSUE TITLE
Bug with editing Person

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1559]
When going into editing a Person's record I have created - Person's username is briefly shown in the form only to be replaced with my own username. I now cannot edit the Person fearing my username will overwrite theirs.

**Comment by maneesha** [comment]
Thanks for raising this issue @anenadic 
I'm not seeing this happen on my end. @sheraaronhurt or @Talishask  could you try and see if you have the same issue?  If not, Aleks - we could try to screen share to see if I can spot anything wrong.

**Comment by Talishask** [comment]
Hi @maneesha, sorry about the delay. 
I just tried editing two people including 'Matthew Gillman' and did not experience the same issue.

**Comment by pbanaszkiewicz** [comment]
Hello @anenadic. I think this is your browser behavior - you may have your login & password saved and the browser replaces contents of `username` field with saved information. However, I think there are three possible ways to check this behavior:

* does it happen when editing profiles you did not create?
* does it happen in the same browser but in a private mode? If you're using Firefox, you can also try running AMY in different container context.
* does it happen in a different browser you don't use daily? Eg. if you're a Chrome user, try in Firefox.

**Comment by pbanaszkiewicz** [comment]
@anenadic can you please update on this issue? Is this still happening?

**Comment by maneesha** [comment]
As we haven't seen this again, I am closing this issue.
