### ISSUE TITLE
Workshop Request Form: Not Adding all Tags Automatically

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1561]
When creating events from the WRF submissions the 'circuits' tag is automatically selected for Mix/Match but no tag is selected for DC, SWC or LC workshop submissions. In all cases, the appropriate curriculum should be automatically selected.

I've experienced this issue with Self-organized submissions, but I cannot speak to workshop requests or workshop inquiries. 

This is not an urgent fix - it just means that I need to add the tag manually.

**Comment by sheraaronhurt** [comment]
For the CO workshops, the tags are not automatically selected. This would be a great addition! 

@Talishask with the Mix/Match workshops, the event could be a mix of all of the curriculums. Unless there is a way for AMY to read the workshop website and know that there are multiple curriculums being covered, then you would need to select the tags yourself. 

The other option would be for at least one of the tags to be automatically selected and you can add the additional tags if needed.

**Comment by Talishask** [comment]
@sheraaronhurt - I think this was prior to us having to select 'online' and 'automated-email' as an additional tags when creating an event, so I was primarily requesting that either LC, SWC, DC or Circuits be selected as a tag automatically when we create an event from the workshop request form. 

However, now that we do have a question to confirm whether the workshop is online, could we automatically add two tags? The curriculum and online, if applicable.
