### ISSUE TITLE
TTT Open applications - check by default

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1562]
On a TTT Event screen we have the option to check this off as allowing open application trainees.  It is unusual that we would have an event that does *not* allow this so this should be checked by default.

**Comment by pbanaszkiewicz** [comment]
@maneesha this looks like an easy thing to change, but can you please link a sample form here so that I confirm?

**Comment by maneesha** [comment]
@pbanaszkiewicz  Not sure if this is what you are asking for - but it is this box that I'd like to see checked by default:
![image](https://user-images.githubusercontent.com/829690/72352511-5ff11300-36b0-11ea-848e-be4b72656a96.png)

**Comment by pbanaszkiewicz** [comment]
@maneesha it's only for "New event" form, correct?

**Comment by maneesha** [comment]
Yes, just new events. If TTT is checked as a tag, then that box should be automatically checked.
