### ISSUE TITLE
Add "Do not publish" checkbox to events

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1567]
We occasionally have events where the host does not want the event published on our websites or anywhere else.  We should have a "Do Not Publish" checkbox on all events so any query can filter by this criteria.

**Comment by sheraaronhurt** [comment]
Haha! This is very very urgent :) And right on time :)

**Comment by maneesha** [comment]
Closing this in favor of #1717

**Comment by pbanaszkiewicz** [comment]
Covered by #1717
