### ISSUE TITLE
Update Contact Field in AMY Events

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1568]
Currently the 'contact:' field in an AMY event lists information pulled from the workshop repo.

The field currently lists multiple email addresses as one continuous string rather than separating them with a delimiter or comma. For example, in this workshop: https://amy.carpentries.org/workshops/event/2019-10-24-gitbash/

With the update of the WRF to request additional contacts, we would like to update the contact field in the AMY event to:
- List the emails from the 'Additional contacts:' field of the workshop request form [in place of the contacts from the workshop website]
- Separate the email addresses with a comma

While this does not cause a work stoppage, it may be an important update to integrate into the typeform survey workflow.

**Comment by pbanaszkiewicz** [comment]
Hello @Talishask. There are two things going on in here.

-----

First:
> The field currently lists multiple email addresses as one continuous string rather than separating them with a delimiter or comma. For example, in this workshop: https://amy.carpentries.org/workshops/event/2019-10-24-gitbash/

The reason for this is that the source website contains the email addresses joined: https://ucsbcarpentry.github.io/2019-10-24-gitbash/ (open source for this website in your browser, it's CTRL+U in Firefox on Windows), line 33:

```html
    <meta name="contact" content="library-collaboratory@ucsb.edujonjab@ucsb.edu" />
```

So I assume the error is in workshop-template.

-----

Second:

> With the update of the WRF to request additional contacts, we would like to update the contact field in the AMY event [...]

Take a look at https://amy.carpentries.org/requests/workshop_request/396/ - it's a request that contains multiple additional contacts. Granted, it looks terrible - should be displayed as bullet points [sidenote: I added a bug #1573 for this]. But it does look like we accept multiple additional contacts in WRF form(s).

It looks like `additional_contact` from `WorkshopRequest` isn't being populated further to `contact` field in `Event`. I think we can somewhat easily change this.

**Comment by fmichonneau** [comment]
@pbanaszkiewicz Would AMY parse the email addresses correctly if there were comma-separated in the website metadata? or should only the first address be included in the metadata?

**Comment by pbanaszkiewicz** [comment]
@fmichonneau the quickest & easiest solution is to display comma-separated addresses in `contact` field separately (ie. only on HTML level), but it wouldn't mean that AMY started interpreting these separate addresses individually.

**Comment by fmichonneau** [comment]
@pbanaszkiewicz I updated the workshop template: now, when multiple addresses are provided for the contacts, they are separated by a `|` like other fields (see https://github.com/carpentries/workshop-template/commit/0594d9a406690dd1fc67ed33c4b4042d8c6848b3). This should make the import of these addresses easier on the AMY side.
