### ISSUE TITLE
Connecting Membership Organisation and Workshops

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1571]
We have received several requests from Member Sites to know how many workshops they have hosted both Centrally-Organised and Self-Organised. We would like to have a way to connect memberships with workshops similar to how Instructor Training seats are connected to Memberships.

**Comment by pbanaszkiewicz** [comment]
Hello @sheraaronhurt. Is this feature request for external API available for Member Sites? If not, you can provide Member Sites with such information by filtering Events in a specific way. For example, if you select specific organisation as a "Host", and "self-organised" as "Administrator", then you list self-organised workshops hosted by this organisation. Example: https://amy.carpentries.org/workshops/events/?assigned_to=&host=374&administrator=343&invoice_status=&completed=unknown&country=&continent=&state=&order_by=

**Comment by sheraaronhurt** [comment]
@maneesha could you help me to articulate what I am looking for. I am not sure if I'm requesting an external API. 

Ultimately, I would like to be able to assign a Membership to Workshops so that we can accurately track how many workshops a Membership hosts (CO or SO). Currently, we use the "Host" option but that isnt really the Membership. 

I was looking for something similar to how we track Memberships and Instructor Training. 

Thanks!

**Comment by maneesha** [comment]
This would be a bigger project, so let's keep some discussion here but it will take work to figure out how to implement this.  There are a few things we are considering:

* Expand how we track memberships in AMY, to include more information about the agreement terms, especially when they fall outside our standard Silver or Gold memberships.
* Connect workshops to memberships.  As Sher noted, this currently happens via "host" but there are many times where the host and the sponsoring member are not the same.  A workshop may happen at a member site but is unaffiliated with the membership.  Also a member site may run a workshop at another site but apply it to their membership.
* We would also like to consider a page for member contacts.  Just as individuals can log in to AMY and view their own record, a member contact can log in and view their membership's details.

We'll consider scoping this out more for a future AMY project.

**Comment by maneesha** [comment]
I am closing this as it is addressed in the current membership project, where we now have the ability to give each workshop a host, sponsor, and member association.
