### ISSUE TITLE
Additional Contacts in Submission

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1575]
Hi Maneeshsa & Piotr,

Can we update the way 'Additional contacts:' show up in the submission email and on the submission page in AMY. The current format makes it difficult to cut and paste the contacts into the CC field of an email.

**Current Format:**
['email@address.com'
'email@address.com'
'email@address.com']
Here is an example: https://amy.carpentries.org/requests/selforganised_submission/367/

**Suggested format:** 
email@address.com,email@address.com,email@address.com
or email@address.com;email@address.com;email@address.com;
--

**Comment by pbanaszkiewicz** [comment]
Related to #1573.

**Comment by pbanaszkiewicz** [comment]
Turns out there's a bug in Select2TagWidget preventing proper value saving or retrieving.

**Comment by pbanaszkiewicz** [comment]
@Talishask can you please test one thing for me? I need to make sure that the following format works well in your email client. Can you please copy these two lines and paste into New Message window in your email client? I tested it in Thunderbird and it was OK (see below for details).

------

Test Person <email@email.com>
Another Person <person@example.com>

------

When I select these two lines above, copy them and paste into New Message window in Thunderbird:
![obraz](https://user-images.githubusercontent.com/72821/71580626-c0ede800-2b01-11ea-9d8b-ca31338d1461.png)
...Thunderbird recognizes line break between the lines and enters a comma there.

Now, take note where my cursor was on the previous screenshot. When I click [TAB], as to move my cursor to the next field ("Temat", ie. "Subject"), Thunderbird splits the field:
![obraz](https://user-images.githubusercontent.com/72821/71580705-08747400-2b02-11ea-9ef1-42c5d97c9da7.png)

Thunderbird behaves exactly the same when I copy your first suggested format ("email@address.com,email@address.com,email@address.com"). However, it doesn't work with semicolons.

**Comment by pbanaszkiewicz** [comment]
@fmichonneau pointed out that the emails should be contained in brackets in the example:
> Test Person \<email@email.com\>
> Another Person \<person@example.com\>

This way they're recognised e.g. by Gmail web interface.

However, I looked through the data in this field and it looks like when people used this field, they only entered email values, never adding a person's contact details. So the examples above shouldn't contain names:

> email@email.com
> person@example.com

(please note lack of brackets)

With only email addresses in the lines, Gmail and Thunderbird easily recognise the addresses.


Additionally, we don't try to fix user-entered values in this field. Ie. we don't try to guess they wanted to use `Personal Family <email>` but they only used `Personal Family email`.

In these cases - please note that there are no such cases yet - I think it's human's job to fix manually the wrong data format for use with the email client.

@Talishask do you agree to keep the display as is then?

**Comment by Talishask** [comment]
I think I understand but just to be sure, I will repeat it here:

The field in our workshop request form asking for additional contacts only asks for an email address. Currently, the submission view displays the contact information in this format:
['email@address.com'
'email@address.com'
'email@address.com']

We can update the format in the submission view to look like this:
email@email.com
person@example.com

Is that correct?

**Comment by pbanaszkiewicz** [comment]
@Talishask:
The format will change from:
> ['email@address.com',
'email@address.com',
'email@address.com']

to:
> email@email.com
> person@example.com

However, we don't fix or guess user-entered format. So they may enter values like "email@email.com", but also "Piotr Banaszkiewicz", "phone 555-555-555" or anything else.

**Comment by Talishask** [comment]
Ok...I understand. That sounds good. 
Thank You @pbanaszkiewicz
