### ISSUE TITLE
Remove Lessons Covered from the Workshops Event Page

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1607]
The Workshop Administration Team discussed the need for having the "Lessons covered" section on the Workshop Event page. We do not need to collect this data and would like to have it removed from the form.

**Comment by ErinBecker** [comment]
Thanks for the issue @sheraaronhurt. I know that on the Curriculum team we get a lot of questions (e.g. from Maintainers) about the relative popularity of different lessons (e.g. the two different SWC R lessons). This has been an active area of conversation in making decisions about archiving certain lessons or keeping them active. Do we have another way of getting information about which lessons are taught if we take this off of the form?

**Comment by sheraaronhurt** [comment]
after speaking with @ErinBecker  we identified that we need to properly label the SWC workshops under "Curricula taught at the workshop". This will help the Maintainers understand the frequency of  workshops are being taught. They should read as follows:

- Software Carpentry (shell, git, Programming with Python)
- Software Carpentry (shell, git, Plotting and Programming in Python)
- Software Carpentry (shell, git, Programming with R)
- Software Carpentry (shell, git, R for Reproducible Scientific Analysis)

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt @ErinBecker after you open AMY, you should be able to click "Hello, NAME" and then "Django Admin". On the next page, find "Curricula" link. It'll take you to the list of curricula that you can edit.

Here's relevant SWC part:
![obraz](https://user-images.githubusercontent.com/72821/72741782-a068f900-3ba8-11ea-99f2-d107591039be.png)

You can either tell me what you want changed and how, or change it yourself.

**Comment by maneesha** [comment]
@ErinBecker  Have you looked at the way curricula are defined in AMY following this issue?  Is there anything more we need to do here?

**Comment by ErinBecker** [comment]
Sorry @pbanaszkiewicz and @maneesha this fell off my radar. I'm putting on the Curriculum Team meeting agenda for next week for us to follow up and will update this issue when we have. Thanks!

**Comment by ErinBecker** [comment]
I just (finally) went in to make these changes and noticed that someone else got there before me. Thank you to whoever it was! Closing. 
![Screen Shot 2020-08-03 at 9 13 35 PM](https://user-images.githubusercontent.com/19176319/89252333-4375e300-d5ce-11ea-9de8-b66b2d3a9d23.png)
