### ISSUE TITLE
500 Server error when 'manual attendance' field is not set

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1608]
Having 'Manual attendance' field unset causes a 500 Server Error. I tried leaving it unset for workshops where the attendance number is not known yet. It defaults to '0' - not sure if this is the desired behaviour (to have attendance at 0). If yes, disregard the issue.

**Comment by pbanaszkiewicz** [comment]
Thanks @anenadic for reporting this. I saw bug emails from AMY but didn't know what caused them.

In this case, this is a bug, because the form should always require numeric manual attendance, event if it's 0 by default.
