### ISSUE TITLE
Accepting WRF - Administrator Field (Removing unused options)

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1609]
The WAT & RC's only use 4 options for Administrator Field: 

- Data Carpentry
- Library Carpentry
- Software Carpentry
- self-oraganised

It would be nice only have those options and not have to scroll through so many. The help text should read "Lesson Program administered for this workshop" or something similar.

**Comment by pbanaszkiewicz** [comment]
Hi @sheraaronhurt. During accepting a Workshop Request (or Workshop Inquiry, or Self-Organised Submission), you actually create an event. And in the split view (data on left, form on right) the form is exactly the same as for "New Event" form.

I suggest swapping "Administrator" label and help text, and limiting available choices to "Data Carpentry", "Library Carpentry", "Software Carpentry", "self organised". I can do that on all Event forms, or on specific forms used in Accepting WRF / WI / SOS, just let me know which one I should change.

**Comment by maneesha** [comment]
We should also add "Instructor Training" to these options. We've been using SWC for historic reasons, but that's not really accurate.  

I think this should apply to all forms.

**Comment by sheraaronhurt** [comment]
@pbanaszkiewicz that works for me. And agree with @maneesha  that we also add "Instructor Training"

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt and @maneesha:

1. What about "Data Carpentry Onboarding" organisation - should it appear in "Administrator" field too?
2. I don't see "Instructor Training" in the list of organisations, either. Can you add it into AMY? I'll work on this issue from there.

**Comment by sheraaronhurt** [comment]
@pbanaszkiewicz no, DC Onboarding should not appear in the Administrator field. 

I will allow @maneesha  to answer the second one

**Comment by maneesha** [comment]
Done!
@pbanaszkiewicz  Please let us know if you need anything else.
