### ISSUE TITLE
Venue, address and latlong info not picked up from workshop URL

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1610]
Just discovered some workshops without location info in AMY and when checked in their workshop websites - location (venue, address and latlong) info was there. Tried updating workshop records in AMY by doing 'update from URL' but it didn't pick up the location data.

**Comment by maneesha** [comment]
Thanks for sharing this @anenadic 
Where did you see that location was missing? Was country also filled in these cases?

**Comment by maneesha** [comment]
Pinging @anenadic - please let us know if this has been happening with specific workshops to help us troubleshoot.

**Comment by pbanaszkiewicz** [comment]
This may be another case of #1572 (no slug on workshop website prevents update from URL), but still it would be very useful if @anenadic provided workshop websites / slugs that caused issues.
