### ISSUE TITLE
Match Secondary Email in WRF

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1618]
Hi Piotr, 
We recently added the option to include a secondary email in AMY's person record. I'm creating this issue to verify or update our person matching for instructor training applications and/or all workshop request forms to the secondary email address if used.

**Comment by pbanaszkiewicz** [comment]
Once matched, person's secondary email gets updated with what's in Training Request secondary email field.

However, secondary email from Training Request was not used to search for matching person. This will be changed.

Workshop requests (and workshop inquiries, and self-organised submissions) aren't meant for creating persons, so they don't offer "match with this person" capability.
