### ISSUE TITLE
Update form fill/validation when creating AMY Events from submissions

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1625]
In this issue (https://github.com/carpentries/amy/issues/1572) we identified some issues that block AMY from pulling workshop information into the event. However, when this conflict exists with the workshop webpage, all of the fields on the 'new event' side are blank. Even the information that is pulled from the workshop request form. 

Can we update the validation/autofill here so that when these hosting or webpage conflicts happen, the information that is pulled from the workshop request form still auto-fills as appropriate on the 'new event' panel? This way we only have to manually add the fields that were pulled from the workshop website?

**Comment by pbanaszkiewicz** [comment]
Ref. #1572.

**Comment by pbanaszkiewicz** [comment]
This is possible duplicate if #1572. Closing for now, I'll present solution in PR and ask @Talishask for verification.
