### ISSUE TITLE
Add date feature to Self-Organised Workshop Request Form

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1644]
There is no date field in the [SO WRF](https://amy.carpentries.org/forms/self-organised/) we would like to add a date field between: "What is the format of this workshop?*" and "Please share your workshop URL". Can use the same feature as the [Centrally-Organised WRF](https://amy.carpentries.org/forms/request_workshop/)

**Comment by pbanaszkiewicz** [comment]
I have a couple of questions:

- Is the field required?
- Should it read "Preferred dates"?
- Should it have a help text?
  > Our workshops typically run two full days. Please select your preferred first day for the workshop. If you do not have exact dates or are interested in an alternative schedule, please indicate so below. Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.

**Comment by sheraaronhurt** [comment]
@pbanaszkiewicz  thanks for the questions! 

- This is a required field
- Bc this is a Self-organised form... the dates are not preferred but actual because the workshop hosts is submitting the information to us directly. 
- Help text could read: Please provide the dates that your Self-Organised workshop will run.

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt important question I need an answer to before implementing this feature: is the field going to store the date of the first day of the workshop? Or do you want a generic text field for user to enter which dates the workshop will run (this will not be machine-friendly)?

**Comment by fmichonneau** [comment]
Given that the dates are known for Self-organized workshops, the fields should store the actual dates for the beginning and the end of the workshop. Thanks!

**Comment by sheraaronhurt** [comment]
@pbanaszkiewicz I agree with @fmichonneau  these should be the exact dates.
