### ISSUE TITLE
TaskForm not working correctly due to prefix change

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1650]
@pbanaszkiewicz 
Adding an instructor for a workshop causes 500 Server Error. Just tried to do so for workshop: https://amy.carpentries.org/workshops/event/2020-04-06-ucl-online. Editing other workshop details worked fine.

**Comment by anenadic** [comment]
Perhaps a related issue - I also got a 500 Server Error when trying to accept a workshop request but then on repeated attempts accepting the request worked so not sure what was happening but thought I should report it.

**Comment by pbanaszkiewicz** [comment]
`TaskForm` send from edit event page has specific prefix, but the endpoint getting data (`TaskCreate` view) doesn't expect it.
