### ISSUE TITLE
Workshops "Update from URL" not updating

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1653]
When I try to update the workshop website in AMY it doesn't do anything. It isn't providing me with a new "Comment Box" showing me the updated instructors/helpers. 

I get the message: **Success: 2020-04-28-genentech was updated successfully** but nothing happens

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt I went to 2020-04-genentech event in AMY and tried updating it by clicking "Update from URL" and then "Update" in the modal window.

The result was that comment box at the bottom was filled with instructor and helper names from that website.

I highly suggest forcing refresh of the website cache. When on event edit page, hit one of [the shortcuts Wikipedia lists](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) (for me CTRL+F5 or CMD+SHIFT+R works), then try again updating from URL.

Feel free to reach out to me on Slack if you need some assistance with diagnosing this issue.

**Comment by sheraaronhurt** [comment]
I did this and nothing happened. It changed the date that I did something but it didn't provide me with a new comment box.... 

Normally, even it nothing changed, when I click the update url it would provide a new box with the date/time and names.

**Comment by Talishask** [comment]
Same. I tried this and it is still not working. I also tried clearing the cache from the settings menu and no change. I haven't been able to pull info from the workshop website for any of the workshops I've been working on so its definitely system wide.
