### ISSUE TITLE
Add Workshop Type to Workshop Request Forms

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1654]
[All of the forms](https://amy.carpentries.org/forms/workshop/) (inquiry, centrally-organised, self-organised) should include a question regarding a workshop being taught online. 

Where will your workshop be taught? 
- in-person
- online

For Inquiry and centrally-orgnised, this should go above "Workshop Location". For Self-Organised the question should go above "What is the format of this workshop?" 

These should be radio button options (only one selection). This is a required question.

**Comment by maneesha** [comment]
I have a pending PR to address this.  See #1655

**Comment by pbanaszkiewicz** [comment]
Ref #1655

**Comment by pbanaszkiewicz** [comment]
Closed via #1704
