### ISSUE TITLE
What is the purpose of git_version.py?

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1656]
What is the purpose of this file? 

https://github.com/carpentries/amy/blob/develop/amy/workshops/git_version.py

It gets updated regularly on my local repo but I have been ignoring it locally as it has been unchanged in the repo in the past two years.

**Comment by pbanaszkiewicz** [comment]
This file is used for displaying the current git commit hash in the AMY footer:
![obraz](https://user-images.githubusercontent.com/72821/81503527-55542c80-92e4-11ea-9e1d-6d4273fcd263.png)

I agree it's a bit cumbersome to use it properly, as it requires regenerating through `make` and some sort of git magic for ignoring changes to this file. (We do regenerate it on the production, though!)

@maneesha if you feel like it, it'd be good to have this file removed from AMY.

**Comment by pbanaszkiewicz** [comment]
It's not enough. `.gitignore` works for files by preventing them being added to the index, while we have to use `git update-index --skip-worktree <file>` command.

I'd propose to get rid of it as it's not super extra useful.
