### ISSUE TITLE
Fixes needed to how lat/lon is treated

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1657]
Latitude and longitude are appropriately stored as floats, for example in the [Airport class](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L397) and the [Event class](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L1015).  

However, because (0, 0) is a valid set of lat/long coordinates,  testing for something like `if not lat` or `if not long` returns false negatives.  See the for example the [admin dashboard](https://github.com/carpentries/amy/blob/develop/amy/templates/dashboard/admin_dashboard.html#L78) and the [event details table](https://github.com/carpentries/amy/blob/develop/amy/templates/includes/event_details_table.html#L55).  

Once this is resolved we should also fix the [default coordinates](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L1322) for online events to be (0,0).

**Comment by pbanaszkiewicz** [comment]
Great catch. We could switch to using NULLs in the database for latitude and longitude when they're undefined (like in case of online event).

**Comment by fmichonneau** [comment]
> We could switch to using NULLs in the database for latitude and longitude when they're undefined (like in case of online event).

:+1:
