### ISSUE TITLE
Fixes to workshop summary in membership view 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1664]
In the Membership summary view, it includes canceled workshops in the completed workshops count.  This should show only workshops that are in the past and have not been canceled/stalled.  "Completed" does not need to checked for it to be counted here.  We'd also like a column for "Planned" for future workshops.  

Also, because there are no limits to self organized workshops, there should only be two columns for completed and planned. 

Here's a sample of what this should look like.
![image](https://user-images.githubusercontent.com/829690/82246275-5b649180-9912-11ea-8047-a337d88798f7.png)

**Comment by pbanaszkiewicz** [comment]
What should be the conditions for `planned` workshops?

**Comment by maneesha** [comment]
`Planned` means that they have an event in AMY but it is in the future.  
`Completed` means they have an event in AMY but it is in the past (and not stalled/cancelled).

**Comment by pbanaszkiewicz** [comment]
Does `planned` have to have both start and end dates? What about required tags?

**Comment by maneesha** [comment]
For `planned` we should have future start and end dates, and tags should not be stalled or canceled.
