### ISSUE TITLE
Include additional contacts from workshop request forms in possible recipients of auto-emails

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1679]
In several contexts (especially for the 7 day post workshop email), it would be useful to include as recipients people listed as additional contacts in the forms.

It seems that it could be useful to create a new role for the workshops "additional-contact" (or something like this). Email addresses listed in the various additional contacts could then be assigned this role when the workshop request forms get converted into an event.

This way the email addresses would easily be accessible to the email templates and these people could be included as recipients to the automated emails.

**Comment by pbanaszkiewicz** [comment]
We have a field `event.contact` ("Additional people to contact") for storing additional contact emails for each workshop. I'm going to use this field in the `PostWorkshopAction`, if you want to include it in other actions too please let me know.

As for the automatic generation of `event.contact`, it looks like the additional contacts from workshop request don't get copied over to `event.contact` during "Accept & Create a new event". If you want me to change this behavior, please create a separate ticket for it.

If you still want to create a new role for keeping additional contacts this way, please also let me know.
