### ISSUE TITLE
Allow editing of recipients in email previews

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1687]
It would be useful to allow RC to edit the list of recipients of queued emails from the email previews.

After discussing this with Piotr, he mentioned that it's possible but the tradeoff would be that if the people change their emails in AMY in the meantime, their old email address would be used in the email.

[This feature was suggested by @elletjies]

**Comment by pbanaszkiewicz** [comment]
Is this issue decided on? @sheraaronhurt are you happy with this tradeoff?

**Comment by sheraaronhurt** [comment]
This is fine with me. We can add a line in the Helpscout template to be sure to let us know if you are scheduled to teach an upcoming workshop so that we can change the email there as well.

**Comment by fmichonneau** [comment]
@pbanaszkiewicz, please go ahead and implement this. The tradeoff is reasonable.

**Comment by pbanaszkiewicz** [comment]
@maneesha feel free to close it if you don't need this feature in the new implementation.

**Comment by maneesha** [comment]
I am checking with the Workshop Admin team to see how they currently use this.
