### ISSUE TITLE
Copy automatically additional contacts from Workshop Request to Event

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1707]
follow up from #1679 

>  As for the automatic generation of event.contact, it looks like the additional contacts from workshop request don't get copied over to event.contact during "Accept & Create a new event". If you want me to change this behavior, please create a separate ticket for it.

Yes, please implement the copying over of the "additional contacts" from the workshop request to the event creation.

**Comment by pbanaszkiewicz** [comment]
This is covered by #1746.
