### ISSUE TITLE
Re-activate fields for pre/post surveys

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1711]
We used to have the fields `instructors_pre` and  `instructors_post` in the `workshops_event` table. The fields still exist but are hidden from view.  We would like to put these fields back in the `Event` view.  These fields will store the html link to view the pre/post survey results for that event.  

Requesting review from @fmichonneau  before working on this task to be sure there are no privacy concerns with storing the survey results links in AMY.

**Comment by fmichonneau** [comment]
The survey link can be generated directly from the slug (we use a salted hash) so there is no need to store it. It can be generated on the fly. The current issue is that the default settings used by R and Python to generate the key from the slug are slightly different and lead to different results. I need to modify the R code to also accept the key generated by the Python algorithm (as I don't think it's possible to do the other way around).

In terms of privacy, including the key in the workshop event page, means that all the regional coordinators will have access to the survey results for all workshops. This is probably ok but we need to consider the implications.

**Comment by maneesha** [comment]
Members of The Carpentries Core Team will be discussing strategies for sharing survey data with workshop hosts and instructors. We'll revisit this issue after that discussion.

**Comment by maneesha** [comment]
@fmichonneau  per our conversation in Asana, can we move ahead on re-enabling these fields?

**Comment by maneesha** [comment]
@pbanaszkiewicz  we have discussed this internally and would like to see these fields re-enabled.  The fields themselves do not need to change.
