### ISSUE TITLE
include option in profiles for people to disable having their information visible on our websites

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1719]
We need a new option "Consent to have my name displayed with workshops I teach on the carpentries website" (maybe a better wording) in the profiles.

We'll use this information in the queries that retrieve the names of the instructors/helpers to generate the feeds that populate our websites.

Options: "yes", "no" (and "unset" when first introduced).

**Comment by pbanaszkiewicz** [comment]
Call 02/15: this will be expanded as part of consent project.

**Comment by maneesha** [comment]
@fmichonneau  @lauryndbrown  Is this covered through the consents project? Should we keep this open?

**Comment by maneesha** [comment]
@fmichonneau was this already covered in the consents project?

**Comment by fmichonneau** [comment]
we have a generic "Consent to making profile public", we could use this information to filter out instructors/helpers from the list of workshops but this isn't part of AMY but our data feeds/redash query. I'll open an issue there to track this.
