### ISSUE TITLE
Gather consent during profile creation

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1749]
During the profile creation, we need to add checkboxes (and store the timestamp for when this consent was given) to ensure that people:

- [ ] are older than 16
- [ ] allow us to transfer their data outside of the EU

**Comment by maneesha** [comment]
@fmichonneau  Should this be in the [instructor training application](https://amy.carpentries.org/forms/request_training/)? Profiles are often created from there.  
Should we also be asking about all the other consents in the instructor training application?

**Comment by maneesha** [comment]
Tagging @lauryndbrown  as this is connected to consents project.

**Comment by maneesha** [comment]
checking in @fmichonneau

**Comment by fmichonneau** [comment]
The consents are asked after profile creation now. Issue around instructor training application tracked in https://github.com/carpentries/amy/issues/2162

**Comment by maneesha** [comment]
@fmichonneau  what about when we create a person's profile (such as a workshop host)?

**Comment by fmichonneau** [comment]
they are being asked when people log in for the first time, but ideally, we'd want to let the person know we create a profile for them. We don't have a workflow for this yet as far as I know.
