### ISSUE TITLE
Viewing events assigned to others

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1752]
Right now AMY lets us see events _"assigned to me", "assigned all", and "assigned to no one"_. Since I manage a team of RC's I would like to be able to see events assigned to other people as well.

**Comment by pbanaszkiewicz** [comment]
Should this be permission-based? For example I can imagine that Sher managing a team or RCs could use:
* assigned to me
* assigned to all
* not assigned
* assigned to: [person]

whereas "regular" RC could see:
* assigned to me
* not assigned

Easier solution (without considering permissions) is to add "assigned to: [person]" option for everyone.

**Comment by maneesha** [comment]
For now it's OK to have it be available to everyone.
One of our upcoming projects will be to have more granular permissions across the AMY platform and we can consider the various options then.

**Comment by sheraaronhurt** [comment]
agree with @maneesha
