### ISSUE TITLE
Introduce warning if membership term is not one year 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1754]
Currently there are no constraints on length of membership term, allowing typos like this for what should be a full year membership. 

![image](https://user-images.githubusercontent.com/829690/99974005-62130c00-2d6e-11eb-8c8a-dca21a411ce2.png)

If the membership term != 1 year then the user should get a warning and be asked if they want to continue.

**Comment by maneesha** [comment]
A few more notes on fixes needed - it appears to automatically populate membership start date and end date as today, and allows for end date to be before start date.

**Comment by pbanaszkiewicz** [comment]
Required changes:
* automatically populate membership end date as today+1yr
* display warning if the selected end date is not (start date + 1yr)

Question (in both cases): should the "+1yr" be understood as the same date with next year (ie. March 20, 2021 -> March 20, 2022), or 365 days (ie. March 20, 2021 -> March 19, 2022)?

**Comment by maneesha** [comment]
@ErinBecker I know we typically don't hold people down to the exact day, but for the purposes of this workflow, could you answer question 1 above?

Question 2 - The warning should be displayed on the new membership form.

**Comment by maneesha** [comment]
@pbanaszkiewicz  I don't want this question to hold you back.  Let's go with same date the following year (March 20, 2021 -> March 20, 2022).

**Comment by pbanaszkiewicz** [comment]
Fixed in #1771.
