### ISSUE TITLE
Support for multiple hosts

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1755]
Some events have multiple hosts. Currently, in the introduction email, only the first host is being used.

Could we make `host` a list like `instructors` and `supporting_instructors`?

https://github.com/carpentries/amy/blob/develop/amy/autoemails/actions.py#L758

```diff
--- context["host"] = hosts[0].person
+++ context["host"] = [instr for instr in hosts]
```

**Comment by sheraaronhurt** [comment]
Can we make it so that only one person is actually named in the email text, but all the others are included when the email is sent?

**Comment by maneesha** [comment]
Just to be clear (as I was confused when I first read this): This refers to the _Host role_, not the _Host organization._

**Comment by sheraaronhurt** [comment]
Yes! The Host Role :)

**Comment by maneesha** [comment]
@pbanaszkiewicz  Please let us know if you have any questions about this issue.

**Comment by pbanaszkiewicz** [comment]
@maneesha @sheraaronhurt @fmichonneau it's all clear for me.
