### ISSUE TITLE
Release notes aren't visible in the docs

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1756]
Release notes (one file for single release) aren't contained in the https://carpentries.github.io/amy/releases/

**Comment by maneesha** [comment]
@elichad  @pbanaszkiewicz  I know you've been doing a lot of work lately on documentation. Is this now complete? What else needs to be done?

**Comment by elichad** [comment]
Looks like we're missing the notes for the last few minor releases (4.0.5-4.0.9) on that page, though they are present in [CHANGELOG.md](https://github.com/carpentries/amy/blob/develop/CHANGELOG.md).
@pbanaszkiewicz did you still want to keep that page maintained, or switch to using the CHANGELOG.md file?

**Comment by pbanaszkiewicz** [comment]
I switched to CHANGELOG that is generated using a script in `docs/generate_changelog.py`.
The remaining releases (up to v4.0.4) are kept as they were since they were hand-written and may contain additional information.

**Comment by elichad** [comment]
Ok, I'll make the move clearer as part of #2374

**Comment by maneesha** [comment]
Closed with above PR.
