### ISSUE TITLE
Slug is being generated incorrectly using workshop location

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1758]
When accepting a workshop request, AMY is auto-generating a slug using the workshop start date followed by the workshop location.  For example:

![image](https://user-images.githubusercontent.com/829690/101506819-d2f81d80-3943-11eb-803a-fbf13972e2e4.png)

This results in invalid characters appearing in the slug.  It also does not follow our standard practice which is to format the slug as `YYYY-MM-DD-hostname`, where the `hostname` is usually a shorthand version of the actual host name.  For example, a workshop on 2020-12-01 at  The University of Pennsylvania Graduate School of Education may have the slug 2020-12-01-upenn-gse.

@sheraaronhurt  @Talishask  Does it make sense for AMY to try to generate a slug in some way, or would it be better to leave that to the human that is accepting the workshop?

**Comment by sheraaronhurt** [comment]
@maneesha definitely think this should be left for the human to decide what the slug is

**Comment by Talishask** [comment]
@sheraaronhurt I thought it did a good job except for the end where it pulled location. If we adjust that part to pull the host domain (minus the .edu or .org part) would that work for CO workshops?

**Comment by sheraaronhurt** [comment]
@Talishask  if it can do what you suggested that would be great! I had thought of that but thought it might be too complex to do.... but it never hurts to share our wishlist!

**Comment by Talishask** [comment]
Cool. @maneesha Could the slug be generated by appending the prefered date to the host domain (minus the .edu or .org part)?

**Comment by maneesha** [comment]
I think that the suggestion from @Talishask  may not work in all situations.  For example, you may have domains like:

*  `www.example.edu` 
* `www.example.edu/library`
* `library.example.edu`
* and so on

We also know sometimes people run concurrent workshops, using slugs like `2020-01-01-example-python` and `2020-01-01-example-r`.  

I think this is probably why we'd want to keep this human generated.

**Comment by pbanaszkiewicz** [comment]
We can change the algorithm to use host name's but in a computerized version. For example:

* Australian Centre for Plant Functional Genomics -> `australian-centre-for-plant-functional-genomics`
* AAAS -> `aaas`
* AMOS Conference (Melbourne) -> `amos-conference-melbourne`

The date part of the slug would stay the same, only the ending would be changed.

**Comment by sheraaronhurt** [comment]
Thanks @pbanaszkiewicz I would like for this to be something that a human decides rather than automated.

**Comment by maneesha** [comment]
@pbanaszkiewicz  in creating a new event from a request, the slug should remain blank, for the human to fill in.

**Comment by sheraaronhurt** [comment]
Thanks so much @maneesha !

**Comment by lauryndbrown** [comment]
@maneesha Right now the help text tells the users to input `YYYY-MM-DD-location`. Should anything change about the text?

**Comment by maneesha** [comment]
@lauryndbrown  That help text is good. Thanks for checking!
