### ISSUE TITLE
WRF Website Slug Validation

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1759]
Can we add a validation message to the URL field of the self-organised notification form?

We already have the suggested format in the help text, so we are wondering if we could add a notification type validation message that could prompt correction if AMY will reject the workshop slug.

**Context**: AMY's slug field includes validation that prevents us from entering events that include underscores in the first 11 characters. For example, 2020-12-15-SITE_LESSON  is an accepted slug but 2020-12-15_SITE_LESSON or 2020_12_15-SITE_LESSON are not. That is okay. 

**Situation**: We currently follow-up on the workshop slug after the form has been submitted and we are hoping to add a validation warning so that those who can change the slug are notified that the slug might need to be changed sooner.

**Request**: For user.github.io links entered into the URL field that do not meet AMY validation for the slug field. Please add a notice that reads: Would you be able to update the slug of the workshop webpage prior to submitting this notification? If so, we recommend using the following slug: YEAR-MM-DD-site-online. If not, that's okay and please feel free to submit the form.

**Request 2**: For user.github.io links entered into the URL field in the repo format github.com/username/slug . Please add a notice that reads: Please adjust the URL format so that it points to the workshop website. The format for this is username.github.io/slug.

**Priority**: Not Urgent. We currently have a manual workaround for the workflows affected by this validation issue.

**Comment by Talishask** [comment]
@maneesha  - please feel free to adjust the wording of the notifications as needed.

**Comment by maneesha** [comment]
This looks good to me.

**Comment by pbanaszkiewicz** [comment]
@Talishask which form do you mean in request 1, and which in request 2?

**Comment by Talishask** [comment]
Hey @pbanaszkiewicz - This is all in reference to the self-organised form.
