### ISSUE TITLE
Prepare automated emails to go automatically for every event

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1765]
Preparation steps:
1. create a tag indicating that an event shouldn't be part of the automation (ie. reversed logic)
2. prepare logic around that tag
3. preselect "automated-email" tag when creating a new event

Once these steps are in place, the second phase is to remove the automated-email tag and drop it from email sending logic too.

**Comment by maneesha** [comment]
@pbanaszkiewicz @sheraaronhurt   Is this still relevant given we are using the automated emails across all workshops now? Are we ready to move to the "do not automate email" tag?

**Comment by sheraaronhurt** [comment]
@maneesha I believe we are. I would like to talk with the RC's and ensure this won't be problematic. I don't forsee any issues.

**Comment by pbanaszkiewicz** [comment]
I guess in scope of this ticket is now to reverse the tag (`automated-email` -> `do-not-automate-email`) and change the logic.

**Comment by maneesha** [comment]
@sheraaronhurt  can we go ahead with this, or would you like to talk to RCs first?

**Comment by maneesha** [comment]
I've talked with @sheraaronhurt  about this and we are ready to go with all emails being automated unless they have the "do not automate" tag.   @pbanaszkiewicz  I think we can close this in favor of #2093
