### ISSUE TITLE
Events assigned to RC's

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1784]
Please improve the UI (either preselect currently logged in user, or provide some shortcut option labelled "Me") for RC' to see the workshops assigned to them. 

This is reference to [issue 1752](https://github.com/carpentries/amy/issues/1752 )

**Comment by pbanaszkiewicz** [comment]
Option 1: preselect currently logged in user (may be difficult).
Option 2: a link after the select to assign to yourself.

Second will be less work.

**Comment by sheraaronhurt** [comment]
@pbanaszkiewicz I am not sure I understand what the 2nd options would look like. Is it possible for you to show a mock?

**Comment by maneesha** [comment]
I think what @pbanaszkiewicz  is saying is 

Option 1: When you open AMY as a logged in admin user, it automatically shows just events assigned to you.
Option 2:  When you open AMY as a logged in admin user, you then click on a link to show just events assigned to you.

If my understanding above is correct,  then we'd prefer option 1.  I **think** this is what the fix by @lauryndbrown  above does. LB - can you verify?

**Comment by lauryndbrown** [comment]
@maneesha thats how I interpreted Piotr’s response as well. I was solving for option 1. So that when the user goes to the admin dashboard they only see events assigned to them by default. They can remove their name from the assigned to drop down to see all events.

**Comment by maneesha** [comment]
Thanks @lauryndbrown ! 
Note that the option to see events assigned to other users should still exist; just by default it should show the logged in user.

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt @maneesha @lauryndbrown yes, that's what I meant 😃 Thanks for translating my gibberish!
