### ISSUE TITLE
Add language to instructor training application about sharing data

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1787]
On the instructor training application, we should have information about how we may share the information in the application.

- If someone is choosing "Pre approved registration" : Please note your application materials and information about your progress towards The Carpentries Instructor certification may be shared with our contacts at your member site.
- If someone is choosing "Open training application" : Please note your application materials may be shared with The Carpentries Trainers in order to review and accept your application.

@fmichonneau @karenword  Can you both review the language above?

**Comment by fmichonneau** [comment]
this seems ok to me. The link to the privacy policy should already be on this page but it'd be good to double check. We'd also want to spell this out in the privacy policy (I'll make a note in Asana about it).

**Comment by karenword** [comment]
LGTM! Thanks @maneesha

**Comment by pbanaszkiewicz** [comment]
Wouldn't you want to have this as a checkbox on the form itself?

If just the text is enough, then we have some notes that we can extend with required sentences. They would appear as part of the text in here ("If you have been invited ..."):
![obraz](https://user-images.githubusercontent.com/72821/107888231-346fd600-6f0b-11eb-8de9-8f75d4e34164.png)
In this case the changes are pretty easy.

**Comment by maneesha** [comment]
Yes, so for "Pre-approved registration" the full help text would read:

> Use this if you have been invited to apply through an institutional membership or other agreement with The Carpentries. Please note your application materials and information about your progress towards The Carpentries Instructor certification may be shared with our contacts at your member site.

And for Open Training Application:

> Submit application for review to receive a scholarship for Instructor Training through our Open Application Program. Please note your application materials may be shared with The Carpentries Trainers in order to review and accept your application.

Note I've also tweaked the existing language to make it read a bit better.

@fmichonneau  there is another check box for them to verify they've read and agree to the privacy policy.

**Comment by lauryndbrown** [comment]
The pr fixing this issue was merged. Closing the ticket.
