### ISSUE TITLE
Filter workshop staff by knowledge domain

### ISSUE THREAD

**Issue by DamienIrving** [carpentries/amy#1788]
I was wondering if it would be possible to add an option to the [Find Workshop Staff](https://amy.carpentries.org/workshops/workshop_staff/) page in Amy so that search results can be filtered by knowledge domain (which is a field each person has in the database)?

That would help when looking for instructors and helpers for research domain specific workshops.

**Comment by pbanaszkiewicz** [comment]
Yes, this is possible.

Note: this requires changes to the `WorkshopStaffFilter` in `amy/workshops/filters.py` - a similar field to `languages` would have to be introduced.
