### ISSUE TITLE
Pre-fill "Assigned to" in WRF

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1804]
When accepting the WRF can the Regional Coordinator/Workshop Administrator automatically be assigned? Since the County has been included we know who the RC is. 

Also, could this also automatically  assign requests to a person too in the [Workshop Request](https://amy.carpentries.org/requests/workshop_requests/) and [Inquiry Request](https://amy.carpentries.org/requests/workshop_inquiries/) and [SO Request](https://amy.carpentries.org/requests/selforganised_submissions/)?

**Comment by maneesha** [comment]
@sheraaronhurt  can you list out here what person goes with what country/region?  In some regions we have more than one RC so we want to be sure to assign to the right person.

**Comment by maneesha** [comment]
@sheraaronhurt  should we still consider this given changes in the RC program?

**Comment by sheraaronhurt** [comment]
@maneesha yes, I would still like to have this because eventually we will have Workshop Administrators in place of RCs. This doesn't have to be a priority though.

**Comment by maneesha** [comment]
@sheraaronhurt  When we have Workshop Administrators, will they definitely be based on country as RCs are now? Or could they be based on some other criteria (like lesson program, domain, etc.)?   When we have multiple WAs for a country, will there be a clear way to know which WA gets a workshop assigned to them?  Let me know if it is too soon to answer these questions.

**Comment by sheraaronhurt** [comment]
@maneesha these are great questions posed and unfortunately, I do not have answers right now. We can/should/will definitely discuss this further once we get closer to bringing on WA's.

**Comment by maneesha** [comment]
I'm deferring this issue for now until we know more about the Workshop Administrator role.

**Comment by maneesha** [comment]
Closing this for now as we will no longer have Regional Coordinators.
