### ISSUE TITLE
Re-assign "Failed" status for training progress

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1808]
In [amy/workshops/models.py](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L2181) there are three `STATES` defined for `class TrainingProgress` : 

```
    STATES = (
        ("n", "Not evaluated yet"),
        ("f", "Failed"),
        ("p", "Passed"),
    )
    state = models.CharField(choices=STATES, default="p", max_length=1)
```

In order to be more open and inclusive of our trainees, we would like to implement the following change:

* Rename the "Failed" state to "Asked to repeat", ensuring that everyone who has a "Failed" requirement now shows as "Asked to repeat." 
* Create a new "Failed" state.  This will be used in extremely rare circumstances, when a trainee has shown inappropriate behavior and we do not want them to try again.

**Comment by pbanaszkiewicz** [comment]
Data migration required, possibly some changes in related UI too.

**Comment by maneesha** [comment]
Looking at this, it may be better to create a new "Asked to repeat" state, move everyone with "Failed" to the new state, and then preserve the "Failed" state.

**Comment by maneesha** [comment]
@lauryndbrown 
If someone has a "failed" status for a Training Progress step, then if we try to award them a badge or try to enroll them in a new instructor training event, we should get a warning saying they failed this step and asking if we are sure we want to proceed.  

Also if someone has  a "failed" status, Notes should be required.  Notes are not required for any other status.

**Comment by lauryndbrown** [comment]
Failed state required:

<img width="894" alt="Screen Shot 2021-03-06 at 7 46 24 PM" src="https://user-images.githubusercontent.com/12959365/110228280-bc1a8600-7eb4-11eb-8347-cf1000889f14.png">
