### ISSUE TITLE
RQ Job Preview for sent mails

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1811]
Currently we can view pending (scheduled) automated email information In the Django administration panel (https://amy.carpentries.org/yikoouxjewu5mri5wmqkufrq6ztk8i5y/autoemails/rqjob/).  However, once the emails go out the details in the preview view go away. This creates a challenge when looking back on a workshop to confirm that an email went out.

Is it possible for the information in the RQ job preview to stay even after the email has gone out?

**Comment by maneesha** [comment]
Tagging @pbanaszkiewicz  for feedback.

**Comment by pbanaszkiewicz** [comment]
I think we can change the setting to keep the successfully sent emails for longer, but they will disappear eventually. What timeframe would suit you, @maneesha @Talishask? A year or so?

**Comment by maneesha** [comment]
Checking with workshop admin team on this: @sheraaronhurt  @elletjies  @Talishask  @danielle06   What do you think?

**Comment by sheraaronhurt** [comment]
yes, I year would be good. We will be able to preview them for a year?

**Comment by pbanaszkiewicz** [comment]
Failed jobs are kept for about 1 year, but those that succeeded by default stay for only 500 seconds.

From what I looked, we can keep succeeded jobs for longer than 500s, e.g. for 1 year (even more if you want).

**Comment by maneesha** [comment]
One year sounds good.  
Is there an advantage to keeping them just one year vs. keeping them longer (or forever)?

**Comment by danielle06** [comment]
I think one year would be good. Usually, when we need to check on an email it's during the life of the individual workshop. I feel like one year would be plenty of "just in case" time. Right now I can't think of an advantage to keeping them for longer than that but I could definitely be missing something.
