### ISSUE TITLE
[Tech] Run black on whole codebase, and provide blame commit rev

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#1812]
Use instructions in here: https://github.com/psf/black/#migrating-your-code-style-without-ruining-git-blame

The objective is to have all Python files reformatted by black, and then the commit that created them should be added to a file; this file will be used to configure `git blame`.

Add instructions for running git blame configuration in the README (since this step is manual for all users).

**Comment by lauryndbrown** [comment]
So one thing that sticks out to me is:

>The one caveat is that GitHub and GitLab do not yet support ignoring revisions using their native UI of blame. So blame information will be cluttered with a reformatting commit on those platforms. (If you'd like this feature, there's an open issue for GitLab and please let GitHub know!)

Looks like folks have requested this feature: https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256
