### ISSUE TITLE
Membership: add cost and currency in table

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1822]
for reporting, we would like to extend the membership model to include the cost and associated currency with each membership so we can answer questions like: "what is the revenue per country"

**Comment by maneesha** [comment]
I had discussed including financial information in AMY with @Talishask 
and I think we decided not to do so.  Talisha, can you remind me what we talked about? This is an easy field to add, but I want to make sure we're not duplicating things that are more officially recorded elsewhere as this increases the chance of errors.  When the money reaches us, it reaches us in US dollars so we'd still need to adjust for conversion rates at the time of transfer and any other fees associated with it.

**Comment by fmichonneau** [comment]
if we do decide to add this to AMY, Erin has mentioned that we'd also want to have the revenue information for out-of-membership centrally organized workshops.

**Comment by Talishask** [comment]
@maneesha - We recently revisited this idea at our meeting and thought adding the cost of memberships would help with our ability to pull data on 'revenue per country'. I can currently pull this data from QB but redash dashboards provide a better level of access to this data. There are a few additional factors and questions that I would have about how we implement this, so could you give me some time to get clarity from Erin and then I will set up a meeting with you.

**Comment by Talishask** [comment]
@maneesha - Erin and I discussed this at our meeting today we realized that adding the price to the membership entry would be relatively easy to do but would not provide a full picture of our revenue by country as this does not take into account things like a-la-carte workshop and instructor training income for example. We have reached out to CI to get some clarity on what we need to track and then I will come back to the infrastructure team to outline a plan forward.

**Comment by maneesha** [comment]
@Talishask  Is this something you'd still like to consider?

**Comment by Talishask** [comment]
@maneesha - I think we do, but we do not have a clear idea of what information we need, how we want to track it, and how it will be used. I will take this back to membership team to outline better what this would look like.

**Comment by maneesha** [comment]
Deferring this until we know more.

**Comment by maneesha** [comment]
OK, then I am closing this issue.
