### ISSUE TITLE
Emails not removed for cancelled events

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1823]
In AMY, after adding a workshop using the WRF submission and the automated-email tag. The self-organised request form confirmation email and 7-days post-workshop email were scheduled. All things working as planned.

However, after realizing we made a mistake, we deleted the workshop event in AMY and received a notice at the top of the screen that the post-workshop email was successfully cancelled. Going into the Django platform we found that the request form confirmation email was still scheduled to go out, so we deleted the email manually via the Django platform.

Can someone look into this?
What we would like to see is that both (all) emails for a workshop that is cancelled or deleted are removed from the schedule so they no longer go out. Ideally, when events are deleted in AMY all of the unsent emails should also be cancelled.

Sorry, I do not have specifics at the time. Let me know if you have any questions.

**Comment by maneesha** [comment]
@pbanaszkiewicz  I know there were some glitches earlier about how emails were queued that you had fixed.  Was this part of that?

@Talishask  Have you still seen this happening?

**Comment by Talishask** [comment]
Since I'm no longer doing this type of admin, I think @danielle06 is the person we want to check with.
Danielle, have you seen any emails going out after an event is cancelled? or have you had to manually cancel emails after the event is cancelled?

**Comment by danielle06** [comment]
@Talishask @maneesha I have not noticed that any emails have been going out after an event is cancelled. I also have not been canceling them.

**Comment by pbanaszkiewicz** [comment]
@maneesha last fix I did for automated emails was unrelated to this. As for the previous fixes, I don't remember.

**Comment by maneesha** [comment]
OK, in that case I will close this issue.  Feel free to re-open or start a new issue if anything else comes up.
