### ISSUE TITLE
Consents: Documentation

### ISSUE THREAD

**Issue by lauryndbrown** [carpentries/amy#1844]
I noticed there are descriptions of the major database tables in the docs. I'm not certain if the work I'm working on should also be added to the documentation as well.

**Comment by lauryndbrown** [comment]
@pbanaszkiewicz would you like me to add consents related tables to the project documentation?

**Comment by pbanaszkiewicz** [comment]
> 
> 
> @pbanaszkiewicz would you like me to add consents related tables to the project documentation?

@lauryndbrown that would be very useful, but I'd say it has lower priority probably.

**Comment by fmichonneau** [comment]
@maneesha you have written some of this documentation in the past. Would you be able/willing to write an initial draft about these new tables?

**Comment by maneesha** [comment]
We have two places where we have AMY documentation.

[This document in GitHub](https://github.com/carpentries/amy/blob/develop/docs/amy_database_structure.md) lists out the most commonly used tables, intended to make it easier for people to write SQL queries in Redash.

[This section of our Handbook](https://docs.carpentries.org/topic_folders/workshop_administration/amy_manual.html) (which needs to be updated anyways) is intended for admin users of AMY to be able to manage data entry and retrieval.

Ultimately, we would need to update both.  @lauryndbrown in your scope of work, do you have notes on what tables are changing and how the UI is changing? That will be useful to write this documentation, and I can start working on that.

**Comment by lauryndbrown** [comment]
@maneesha I'm afraid I do not have notes. I can make some, though it might be somewhat similar to writing the documentation. I should probably write the documentation on the tables. Can you give me a sense of what you would need from me? For the section of the handbook if you'd like to tackle that? It looks like a list of UI changes.

**Comment by maneesha** [comment]
Hi @lauryndbrown I don't know right now what tables and fields are changing, but once everything is released, it would be great if you could update [the database structure overview](https://github.com/carpentries/amy/blob/develop/docs/amy_database_structure.md).  I can then work on the UI in the handbook.  What do you think?

**Comment by lauryndbrown** [comment]
Sounds great @maneesha. I started the PR. I'll polish it in a few hours, and tag you.
