### ISSUE TITLE
Add "Withdrawn" state to Instructor Training Application

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1879]
We currently have the states Pending, Accepted, and Discarded.
We should also have the state Withdrawn. This will be used when a trainee informs us they are no longer interested in the Instructor Training program.

@klbarnes20 @karenword  what do you think?

**Comment by klbarnes20** [comment]
I think this is a great idea!

**Comment by maneesha** [comment]
@pbanaszkiewicz Noting here we'd like to go ahead with this.
