### ISSUE TITLE
Consents: Remove old-style consents stored on the Person Model.

### ISSUE THREAD

**Issue by lauryndbrown** [carpentries/amy#1881]
There are three pre-existing consents that are in the Person model:
- publish_profile
- may_contact
- lesson_publication_consent

It appears they show up:
- person_merge.html
- person.html
- trainee_dashboard.html
- api:export-person-data

I don't see any other functionality attached to them.

This ticket represents the work to remove these references (or replace?).

**Comment by lauryndbrown** [comment]
@fmichonneau  do we want the consents that are already existing to be migrated over, so should users be emailed to reconsent?

**Comment by fmichonneau** [comment]
Current consents need to be migrated to the new system (invisibly to current users).
Existing ones will remain in the database during the initial release of the consent system, and will be deleted in the subsequent release.

**Comment by bencomp** [comment]
Just checking: do I understand correctly that this issue is why my consent to publish my profile and name is not showing in my AMY profile? Then I don't need to open a new issue :)

**Comment by lauryndbrown** [comment]
@bencomp yes that's likely the cause but could you say more or file an issue so that I better understand the problem?

**Comment by bencomp** [comment]
When I log in to AMY, I see on my profile (trainee dashboard):
| Q | A |
|----------------------|------------------------------|
| Do you consent to publish your profile on The Carpentries website? | (decline) |
| Do you consent to have your name or identity associated with lesson publications? | Unset |

When I go to Update Profile, I see

| Q | A |
|----------------------|------------------------------|
|  | [x] Consent to make profile public |
| Do you consent to have your name or identity associated with lesson publications? | Yes, and use the name associated with my ORCID profile |

I can save this again and I do see a message "Succes: your profile was updated.", but these settings have not changed.

I can create a new issue about this, but this issue looked related.

**Comment by bencomp** [comment]
Not sure if anything changed, but I just browser-refreshed the dashboard (while it had the "Update success" banner at the top) and now I do see the correct values. It doesn't make sense to me that a page that has "Update success" would not show the new values, but my issue seems to be solved.

**Comment by lauryndbrown** [comment]
@bencomp I was able to replicate the issue. It is not related thank you for reporting it. I'll work on fixing the issue.

**Comment by lauryndbrown** [comment]
I created an issue with the problem https://github.com/carpentries/amy/issues/1991

**Comment by bencomp** [comment]
I'm a bit late to this, but thanks for fixing it, @lauryndbrown!
