### ISSUE TITLE
Archive Profile: Change permissions should be unset

### ISSUE THREAD

**Issue by lauryndbrown** [carpentries/amy#1889]
Under “Change Permissions”, “is active” should switch to “no”; any custom permissions should be removed, ~GitHub login should get disabled~

Created a separate issue for disabling github login: https://github.com/carpentries/amy/issues/1920

**Comment by pbanaszkiewicz** [comment]
Not every user has access to AMY through email login. If profile archival disables github login, they will not be able to log in back.

**Comment by fmichonneau** [comment]
> If profile archival disables github login, they will not be able to log in back.

@pbanaszkiewicz, yes that is intended. As they asked for their profile to be archived, they should not be able to log into AMY.

**Comment by lauryndbrown** [comment]
Is active is unset already with https://github.com/carpentries/amy/pull/1905
