### ISSUE TITLE
Consents: Feeds need to be updated to read new consents

### ISSUE THREAD

**Issue by lauryndbrown** [carpentries/amy#1895]
Fix feeds scripts that rely on consents

From Manesha:

>yes, we run queries in Redash combined with some Python, R, and shell scripts and send results to feeds.carpentries.org
See this repo for more info: https://github.com/carpentries/feeds.carpentries.org
This uses scripts like this for example, which gets JSON data via Redash's API and parses it with jq to create feeds that serve our websites.
When the changes LB Brown is working on go live we may need to change these scripts  and/or the SQL queries in Redash.

Blocked on https://github.com/carpentries/amy/issues/1870

**Comment by fmichonneau** [comment]
After deployment of the consent system, queries will be updated to use the new consent tables. Given that previous consents will still be present in the database after the initial release, the update of the queries can be done soon after the release.

**Comment by lauryndbrown** [comment]
cc @pbanaszkiewicz for visibility

**Comment by fmichonneau** [comment]
I updated the queries in redash to use the new data model for publication consent.
