### ISSUE TITLE
Change helptext on Workshop Request Form dates

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1899]
On the [Workshop Request Form](https://amy.carpentries.org/forms/request_workshop/) we have the following help text for selecting workshop dates:

>Our workshops typically run two full days. Please select your preferred first day for the workshop. If you do not have exact dates or are interested in an alternative schedule, please indicate so below. Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.

This should be expanded to be:

> Please select your preferred first day for the workshop. If you do not have exact dates or are interested in an alternative schedule, please indicate so below. Because we need to coordinate with instructors, a minimum of 2-3 months lead time is required for workshop planning.
> 
> The preferred dates are not a guarantee. We do our best to schedule your workshop for the dates that you have requested, however, a high volume of workshops on a given date may prevent us from fulfilling your request. Please prepare alternative dates in the event that we can not accommodate your request.

The new text was provided by @sheraaronhurt  and @danielle06

**Comment by danielle06** [comment]
Thanks Maneesha!

**Comment by pbanaszkiewicz** [comment]
@danielle06 @sheraaronhurt @maneesha FYI the same help text appears on the Inquiry form: https://amy.carpentries.org/forms/inquiry/

If you want to change it there as well, please let me know or create a new ticket.

**Comment by maneesha** [comment]
Yes, this should apply to the inquiry form as well @pbanaszkiewicz
