### ISSUE TITLE
Consents: Use Mailgun's Bulk email send rather than sending individual messages to the user

### ISSUE THREAD

**Issue by lauryndbrown** [carpentries/amy#1904]
See this comment for the discussion: https://github.com/carpentries/amy/pull/1872#discussion_r607566498

**Comment by lauryndbrown** [comment]
cc @pbanaszkiewicz I'll circle back around sometime next week and see if I can't get a mailgun sandbox account. If you have access to one for AMY that would be great.

**Comment by pbanaszkiewicz** [comment]
@lauryndbrown I think @fmichonneau has all the accesses.

**Comment by lauryndbrown** [comment]
@pbanaszkiewicz he spoke with me about it. Thanks. I'll take a look at this later this week.
