### ISSUE TITLE
Feedback analysis

### ISSUE THREAD

**Issue by bkmgit** [carpentries/amy#1955]
There is currently a [Carpentries feedback facilitation program](https://github.com/carpentries/community-facilitators-program). One of the issues raised is how to effectively obtain a summary of feedback from the numerous channels that the Carpentries uses. For written feedback, natural language processing and machine learning may be useful tools. Might it be possible to incorporate some of these in AMY?  Other communication channels could then be converted. For example for Twitter, mailing list and chat application data.

**Comment by pbanaszkiewicz** [comment]
@maneesha @sheraaronhurt @Talishask tagging you on this ticket, perhaps you have some thoughts on this feature request.

**Comment by bkmgit** [comment]
Am happy to implement this.

**Comment by maneesha** [comment]
Hi @bkmgit  Thanks for making a suggestion.  Can you share some more details about what you are thinking of? 

AMY is a database platform that The Carpentries uses to track activity around instructor training and technical workshops.  I'm not sure how feedback facilitation would fit into this, but am happy to hear your suggestions.

**Comment by bkmgit** [comment]
@maneesha Thanks for your reply. AMY seems to just generate links to the surveys, and does not actually store the survey data. There appears to be some possibility of automating giving instructor feedback in https://github.com/carpentries/instructor-feedback   - not sure what is used to store the survey data.  However, a summary of the data and possibly tagging of comments as positive or negative sentiment, as well as topic clustering of free responses may be helpful in suggesting actions that should be taken.

**Comment by maneesha** [comment]
Links to surveys are not generated within AMY at all.  
As for the data itself, survey data is generally considered confidential and is only shared with the organizers and instructors of a workshop.  It sounds like you have some good ideas in the instructor feedback repo, but this is not connected to any data AMY stores.  I'm closing this here and look forward to seeing your work in the other project! 

Feel free to re-open or raise a new issue if you still have questions.
