### ISSUE TITLE
Profile Feature Request: Accessibility of the "Workshop Activity" Table

### ISSUE THREAD

**Issue by annajiat** [carpentries/amy#1968]
It might be helpful if we could improve the accessibility of the "Your workshop activity" table at https://amy.carpentries.org/dashboard/trainee/ by enabling the users to sort the table by the available columns:

- Workshop name
- Venue
- Your role
- Dates  (may be made the default sort order: newest to oldest with non-date entries placed at top)

Currently they are listed in seemingly random order. 2021, 2020, 2021, blank. 2020, etc.

**Comment by annajiat** [comment]
The boxes to filter table entries at the following page can be adopted as well
Browse Community Developed Lessons
https://carpentries.org/community-lessons/#the-carpentries-incubator

**Comment by maneesha** [comment]
Thanks for bringing this up.  Right now, your tasks are sorted by task and date.  I'm closing this issue as we have [another issue open requesting these features on all tables](https://github.com/carpentries/amy/issues/1512).  

@annajiat if you have any other concerns please feel free to re-open this or raise a new issue.
