### ISSUE TITLE
Profile: Update List of Airports

### ISSUE THREAD

**Issue by annajiat** [carpentries/amy#1969]
At https://amy.carpentries.org/dashboard/trainee/autoupdate_profile/
We may need to update the "nearest airport" drop down list. It may be missing some airports, for example, the following international airport is missing which started its operations in 1980.
iata code DAC (icao code VGHS)

**Comment by maneesha** [comment]
Hi @annajiat Thanks for the suggestion. This is not intended to be comprehensive list of all airports. Rather they are added to the list as needed based on our community.  If needed, new airports can [be added by an admin user](https://docs.carpentries.org/topic_folders/workshop_administration/amy_manual.html#adding-a-new-airport).  Individuals can contact team@carpentries.org if their own airport should be added.

I'm closing this, but if you have other concerns please feel free to re-open to raise them.
