### ISSUE TITLE
Changes to Host & Sponsor Labels for Event view

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1992]
Current event view includes these three fields:

![image](https://user-images.githubusercontent.com/829690/124815499-58bd6500-df35-11eb-9736-7578f8879a25.png)

The following changes are requested:

Host should be renamed "Host Site" and should be required.
Sponsor should be renamed "Organiser" and should be required.
Membership can remain as is, and should be optional.

Note in the majority of cases, Host Site and Organiser will be the same.

**Comment by maneesha** [comment]
@pbanaszkiewicz  @elichad  We had a PR come in for this that has been sitting idle.  Should we have merged it? Is there anything else to do?

**Comment by pbanaszkiewicz** [comment]
@maneesha I thought I had reviewed that PR and it had required some improvements. I can't see my comments now, so I guess I'll mark it with v4.2 and review and fix when we start working on v4.2 release.
