### ISSUE TITLE
Add Data Carpentry Astronomy to WRF

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1995]
We have added a new curriculum: Data Carpentry Astronomy. 

This needs to be added to the "Which Carpentries workshop are you requesting?" section for all 3 WRF. 

This also needs to be added to the list of "Curricula taught at the workshop" when accepting the WRF in AMY.

**Comment by fmichonneau** [comment]
these entries come from the curricula which can be added directly in the AMY admin interface. I added it there and it shows across the forms.
