### ISSUE TITLE
Update colors of progress states

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1999]
The current color scheme for our progress states makes it hard to know when something needs further attention and when it does not. Previously we had three colors: Red-Failed, Yellow-Not evaluated yet and Green-Passed. 

The new 'Asked to Repeat' progress state option  is also yellow and so it conflicts with the 'Not Evaluated Yet' option.

**Please update the color for 'Asked to Repeat' to blue.. Any shade will do.**

Progress state colors can be viewed on the [More>Trainees page ](https://amy.carpentries.org/trainings/trainees/)

**Comment by pbanaszkiewicz** [comment]
New color @Talishask:
![obraz](https://user-images.githubusercontent.com/72821/128611076-23afaca3-b8b5-4410-a3aa-548fc64cb7b2.png)

**Comment by Talishask** [comment]
@pbanaszkiewicz - I really like those colors.
