### ISSUE TITLE
Training Status should be "Failed" rather than "Ask to Repeat"

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2001]
This follows up on #1808 

While training status for the three checkout steps (DC/LC/SWC Homework, Demo, and Discussion) should be *Asked to Repeat* rather than *Failed* we do want the Training to be *Failed* rather than *Asked to Repeat*.

I think this would require an update such as 

```
SELECT *
FROM workshops_trainingprogress
WHERE requirement_id = 1
  AND state = 'a';


UPDATE workshops_trainingprogress
SET state = 'f'
WHERE requirement_id = 1
  AND state = 'a';
```

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm not 100% clear on what is required by this ticket. Do you want me to run 1-off query and change values in production database?

**Comment by maneesha** [comment]
Yes, this reflects a change to data, not a change to code.

**Comment by pbanaszkiewicz** [comment]
Done. I'll upload the first query results to you on Slack.
