### ISSUE TITLE
Roll over seats/workshops after new membership created 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2004]
With the new membership features, we have the ability to create a new membership from an existing one, rolling over any or all of the unused instructor training seats and workshops.  This is useful when we know that we'll be rolling over the seats and/or workshops at the point of creating a new membership.

Sometimes we decide to roll over unused seats after the new membership is created.  We would like to have a way to roll over seats after the new membership is created.

**Comment by pbanaszkiewicz** [comment]
Wouldn't https://github.com/carpentries/amy/issues/1936 solve this issue?

**Comment by maneesha** [comment]
We would want to be able to roll over seats when a new membership entry was created independent of the old one.

So we had an existing membership, University X from 2020-07-01 to 2021-06-30.  We created a new membership for University X from 2021-07-01 to 2022-06-30 by creating an entirely new entry, not by rolling over the old one.  We'd like to now make this be a rolled over membership.

This is likely going to be the case for a few current memberships, where the roll over feature was not implemented yet.  I'd also be happy to do a data migration for now and not add in another feature,  knowing that all future memberships should be using the new rollover feature.

**Comment by pbanaszkiewicz** [comment]
@maneesha if data migration suits you, I'd rather do it this way. Unless you're certain the same situation can happen in future.

**Comment by maneesha** [comment]
I think the same situation happening in the future is highly unlikely, so a data migration should be fine.  The only reason for it now is because of current memberships that were entered in before the rollover feature was enabled.  @pbanaszkiewicz what information (and in what format) do you need from me to do the migration?

**Comment by pbanaszkiewicz** [comment]
@maneesha I'll need to know memberships (old, new) and how many seats I should roll over from all categories.

**Comment by maneesha** [comment]
I am closing this because it is old and I don't think we need it as we have been rolling over memberships for two years now.
