### ISSUE TITLE
Issue membership extensions by date, rather than number of days

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2005]
Right now we can issue membership extensions by X number of days.  This is useful for rough guidelines but can cause confusion when it comes to exact dates.

For example, Membership X was supposed to end 2021-07-23.  We grant a three month extension, so the new end date should be 2020-10-23.   AMY requires extensions to be entered by number of days.  Entering a 90 day extension would make the end date by 2021-10-21.  This small difference can cause confusion when we communicate with member sites.

We would like to change this interface so the user enters in a new end date from a calendar, leaving AMY to calculate the datediff.

@Talishask  Please let me know if I've captured this issue accurately and completely.

**Comment by pbanaszkiewicz** [comment]
@maneesha @Talishask I thought of this case when implementing the extension form. That's why there's a recalculated field with new agreement end date:

![membership_extension_form](https://user-images.githubusercontent.com/72821/126901176-a3b7b383-4ccb-4321-ac5e-5dfbc657869f.gif)

Are you sure you want to rework this form?

**Comment by maneesha** [comment]
What is in the screengrab above is OK as a workaround, but ideally we would want to be able to input the date and have number of days automatically calcuate.  Low prioirty.

**Comment by Talishask** [comment]
@maneesha - Yes, the idea is captured accurately and appropriate. 
I also agree that the option to see the new end date before submitting is okay but a workaround to the ideal option of selecting the desired end date.
