### ISSUE TITLE
Include survey links in instructor profile view

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2016]
When a person logs in to AMY, they can see their own profile with a list of workshops they have taught.  Next to each workshop we would like to see a link to the survey results for that workshop (coming from the links in that event's page).

**Comment by maneesha** [comment]
As a follow up to this - this will typically be just one link because our survey tool creates a single link to view pre- and post-workshop surveys.  Right now this is not the case for Instructor Training, which uses a different tool and has different links for pre- and post- results.  

@fmichonneau two questions
1.  When will instructor training use the same system as workshops?
2. Is it possible to integrate the survey results app with AMY so we don't have to manually enter the link in AMY?

**Comment by fmichonneau** [comment]
>  When will instructor training use the same system as workshops?

We are piloting the first instructor training to use the same system with events that are running in September for a full transition by the end of the year.

> Is it possible to integrate the survey results app with AMY so we don't have to manually enter the link in AMY?

not easily at the moment.

**Comment by maneesha** [comment]
OK.  For now we should keep both survey link fields in AMY, and change to just one by the end of the year.

We'll revisit integration of the survey results app with AMY at another time.

**Comment by pbanaszkiewicz** [comment]
To be clear:

1. all events, except for Instructor Training events, should be listed with links to their post-workshop survey results
2. we're only saving link to the survey itself, so post-workshop survey results link needs to be generated
3. to generate the link we're using salts; the results should be available at workshop-reports.carpentries.org, correct?

**Comment by pbanaszkiewicz** [comment]
Notes from meeting with @fmichonneau:

1. Use a new field inside `Event` for storing survey results link
2. Show the link to instructors teaching particular workshop in their profile pages.

**Comment by maneesha** [comment]
We are currently recording these urls in the [Pre-workshop assessment survey for instructors](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L1398) field in the Event view.  Is there a reason we'd need to create a new field in the `Event` model?

**Comment by maneesha** [comment]
Note that the survey links should only be visible when the event ROLE is one of the following:

* Host
* Instructor 
* Supporting Instructor

Survey links should not be visible for any other role.
