### ISSUE TITLE
Community Roles: disallow creating `Task` for instructor/trainer, who has been inactivated

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2025]
As an admin user, I want to be unable to create a trainer or instructor task for a person, whose `trainer` or `instructor` community role has been inactivated.

Acceptance criteria:
* adding instructor or trainer task to an event is blocked if related person's instructor or trainer community role is inactive
* adding instructor or trainer task to a person is blocked if related person's instructor or trainer community role is inactive
* creating instructor or trainer task is blocked if selected person's instructor or trainer community role is inactive

**Comment by maneesha** [comment]
@pbanaszkiewicz  has this been completed?

**Comment by pbanaszkiewicz** [comment]
@maneesha No, not yet. I'll work on it this week.

**Comment by pbanaszkiewicz** [comment]
@maneesha This is what I'm implementing:
1. Adding instructor task is blocked if person has no active instructor community role
2. Adding instructor task to TTT event is blocked if person has no active trainer community role

The difference is that:
1. Person could potentially have multiple instructor or trainer community roles, and I'm checking if all of them are inactive
2. Acceptance criteria were defined as if either inactive instructor or inactive trainer community role would block adding a task. Instead I switched to checking for inactive instructor community role for instructor task, and inactive trainer community role for trainer task (instructor in a TTT event).
