### ISSUE TITLE
Counting workshops with memberships

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2051]
I have seen some discrepancies in how workshops are being counted on the membership page. For example: 

On a [member view page like this](https://amy.carpentries.org/fiscal/membership/253/) we see that  they have completed 4 of 6 allowed workshops plus 1 self organized workshop.

Yet when I do `SELECT * FROM workshops_event WHERE membership_id = 253`  I get 8 workshops total (1 self organized and 7 centrally organized).  

Where is this discrepancy coming from?

**Comment by pbanaszkiewicz** [comment]
The membership ended Aug 05, which makes some of ASU events fall out of calculated numbers.

Here are the events and why they are not counted in:

| name | reason |
| ------ | ------ |
|`2020-12-07--agave-shell-intro` | self-organized|
|`2020-12-14-asu` | tagged as `stalled`|
|`2021-01-18-tempe` | valid (even though tagged as `unresponsive`)|
|`2021-03-08-asu-online` | valid|
|`2021-06-14-asu-online` | valid|
|`2021-07-06-asu-online` | valid|
|`2021-08-16-asu-online` | outside membership agreement dates|
|`2021-09-10-asu-online` | outside membership agreement dates|

As you can see in the table above, only 4 entries are valid and these are the 4 counted on the membership page.

**Comment by maneesha** [comment]
Ok.  Now that we have the membership field in `workshops_events`  this should be used for assigning a workshop to a membership, not the membership valid dates.
