### ISSUE TITLE
Allow zero values for rolled over benefits

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2056]
In creating a new membership by rolling over an existing one, when you try to hit submit, it takes you back to the input for "Public instructor training seats rolled from previous." 
I'm guessing this is because zero values are not allowed here.  They should be - we will often have memberships where no instructor training seats or workshops are rolled over.  Roll over values will likely be the exception.

**Comment by pbanaszkiewicz** [comment]
Note: this behavior doesn't apply to workshops without admin fee, as their calculations are quite different from training seats.
