### ISSUE TITLE
Instructor Selection: confirm or decline signups

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2065]
As an admin user, I want to be able to confirm or decline signups from either event signup listing, or from all events signup listing.

Acceptance criteria:
1. Clicking "Confirm" adds a task for instructor (or supporting instructor) for this user and this event - this should trigger email automation mechanism (EDIT: "confirm instructor for the workshop", but not "introduce Host with Instructors")
2. Clicking "Confirm" changes signup status to "confirmed"
3. ~~Clicking "Decline" sends an email "Thank you for your interest… we have placed other Instructors… please continue to …."~~ (EDIT: moved to #2066)
4. Clicking "Decline" changes signup status to "declined"
5. Once confirmed or declined, signup entry may not be edited _by the user_.

UPDATE 2021-10-18: updated according to @maneesha comment down below.

**Comment by maneesha** [comment]
If we confirm an instructor and then have to decline, that would happen through personal communication and would not be part of this system.
