### ISSUE TITLE
Instructor Selection: close recruitment process

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2066]
As an admin user, I want to be able to close the recruitment process and allow no more sign ups.

Acceptance criteria:
1. From event signup listing, user can click "Close signups" button
2. Clicking this button changes the recruitment from open to closed and shows a notification snackbar
3. The button should only be available when there are no pending signups.
4. After the process has been closed, the email introducing Host and Instructors should be sent.
5. After the process has been closed, the emails to declined instructors should be sent ("Thank you for your interest… we have placed other Instructors… please continue to ….")

UPDATE 2021-10-18: updated according to comment down below and in #2065.

**Comment by maneesha** [comment]
The automated email introducing Hosts and Instructors should go out after the recruitment process has been closed.

**Comment by pbanaszkiewicz** [comment]
Maybe a good work-around would be to add additional condition for the Instructors Host Introduction:
`and event doesn't have open instructor selection`.

**Comment by maneesha** [comment]
We have another project I'm working on now where we are making some changes to our current automated emails. This includes the content and the triggers for when certain emails get sent out. In the next month or so I'll be sharing a plan documenting all of this.
