### ISSUE TITLE
Instructor Selection: view Upcoming Teaching Opportunities on instructor page

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2067]
As an instructor user, I want to be able to view upcoming teaching opportunities (events with open recruitment process).

Acceptance Criteria:

- [x] 1. Button "View Upcoming Teaching Opportunities" is visible on instructor profile (trainee dashboard).
- [ ] 2. The button "View Upcoming Teaching Opportunities" is visible only to active badged instructors (relates to Community Roles project).
- [x] 3. This button takes user to another page: list of upcoming teaching opportunities
- [x] 4. Top of "List of upcoming teaching opportunities" page contains snapshot of instructor's profile and link to go back to main page.
- [x] 5. The list supports filtering and sorting by basic criteria
- [x] 6. The list contains: opportunity name and location (e.g. "Data Carpentry at Some University"), dates and times with conversion tool link, specific location, curriculum and notes from admin

**Comment by maneesha** [comment]
We'd like to consider having each event have some sort of priority flag.  This could be a red/yellow/green icon or other UI feature.  This will indicate whether the workshop is in urgent need of Instructors based on criteria like number of existing sign ups, how far out the workshop date is, etc.  The project team will develop these criteria and share them here.

**Comment by maneesha** [comment]
For point 4 - we should define what we mean by "basic criteria."  
@pbanaszkiewicz  if this is something that is already defined in AMY, please let us know.  Otherwise we can come up with some criteria we'd like to use.

**Comment by pbanaszkiewicz** [comment]
@maneesha 
1. Regarding priority flags: sounds like an interesting extension. I'd like for this to be another story.
2. Regarding "basic criteria" for filtering. Since this wasn't said explicitly, I was thinking about filtering by available teaching opportunity fields or related objects (e.g. workshop dates, places, priority flags, etc.). You can definitely provide what you want to filter on, or we can work this out during the feedback loop.

**Comment by pbanaszkiewicz** [comment]
@maneesha story created for the team (#2083). You can post filter criteria here - I will amend this story.
