### ISSUE TITLE
Instructor Selection: instructor signup form

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2068]
As an instructor user, I want to be able to sign up for upcoming teaching opportunities from the list of opportunities page.

Acceptance Criteria:
1. User can sign up for any upcoming opportunity
2. For in-person workshops, user can express their interest in whole session
3. For on-line workshops, user can express their interest in the whole session ~~, part of the session, or as Supporting Instructor~~ (EDIT: removed as per comment below)
4. User can add notes to their signup
5. If user has already expressed interest in particular teaching opportunity, and their application is pending, they can see "Interest expressed, confirmation pending..." and a button to cancel the application with optional notes
6. Submitting the form should result in success notification snackbar.
7. User should get an error and not be able to continue if they are signing up as interested and the workshop dates conflict with dates they already have Instructor role for a workshop.
8. User should get a warning and be able to continue if they are signing up as interested and the workshop dates are within 14 days of a workshop they are already teaching 
9. User should get a warning and be able to continue if they have signed up as interested for a workshop on those same dates.
10. ~~User should get a warning and be able to continue if they have taught <3 workshops and sign up for regular (not supporting) instructor for online workshops.~~ (EDIT: removed as per comment below)

**Comment by maneesha** [comment]
We are removing the role of Supporting Instructor so item 10 above should be removed.
