### ISSUE TITLE
Instructor Selection: resign from upcoming teaching opportunity

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2069]
As an instructor user, I want to be able to resign from a workshop I have previously applied for.

Acceptance Criteria:
1. "Resign" or "Change option" button should be visible for instructor user on "Upcoming teaching opportunities" list for each workshop they have applied for.
2. The button can only be available for pending applications; once confirmed or declined, instructor has no possibility to resign via AMY interface.
3. Once clicked on the button, user resigns from the workshop (without providing reason).
4. After confirming, a notification snackbar is shown and user's application is withdrawn from the instructor selection for that workshop.

EDIT 2021-10-18: removed reason from pt 3.

**Comment by maneesha** [comment]
Point 3 - we do not want to ask instructors their reason for resigning.
