### ISSUE TITLE
Count Instructor and Trainer roles separately

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2072]
Currently we see all "Instructor" roles counted together, regardless of whether they were at a technical workshop or instructor training.  So the view looks like this:
![image](https://user-images.githubusercontent.com/829690/135506936-c4f2a77f-2b22-452d-9924-7a4738e03623.png)

We would like to see Instructor role for  Instructor Training separated out as Trainer, so it would look like this. 

![image](https://user-images.githubusercontent.com/829690/135506904-989e2470-4fb4-4117-bd2d-083c3720879e.png)

Instructor count: where instructor role is at event with administrator == SWC, DC, LC, or self organized
Trainer count: where instructor role is at event with administrator == Instructor Training

**Comment by pbanaszkiewicz** [comment]
Change it on the user profile page.

**Comment by maneesha** [comment]
Bumping this up because it will become more relevant with the instructor recruitment project.  For that, since we need to distinguish roles at instructor training vs DC/LC/SWC workshops, we want to be sure to list Instructor and Trainer counts separately.
