### ISSUE TITLE
Instructor Selection: Admin sign up for Instructor

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2082]
Not sure if this should be included in an existing issue.

An admin user should be able to sign up an active Instructor on their behalf as interested in a given workshop.

**Comment by pbanaszkiewicz** [comment]
Button should be below the table visible for the admin.

**Comment by maneesha** [comment]
Re-opening this as I don't think it would work as it is.  I don't see a way for an admin user to express interest in teaching on behalf of an instructor.  Note this is different from actually assigning them to teach that workshop.

**Comment by pbanaszkiewicz** [comment]
I'm not sure why this was moved to "done". I don't remember working on it, and there's no pull request linked.
