### ISSUE TITLE
Instructor Selection: priority flags

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2083]
As an admin user, I want the various signup processes to have priorities set automatically. Additionally, I want to be able to manually override and set the priority level.

Priority levels for online workshops:

- High: <= 30 days away
- Medium: 30-60 days away
- Low: >= 60 days away

Priority levels for in person workshops

- High: <= 60 days away
- Medium: 60-90 days away
- Low: >= 90 days away

**Comment by maneesha** [comment]
The priority level should be 
* automatically set when certain criteria are met (i.e. workshop is < 30 days away and is online OR workshop is < 60 days away and is in person, etc.).  We will be defining these criteria.
* option to manually set by the admin.

The instructor user should then be able to filter by priority level.  The instructor user can then choose to view only those that are high, medium, or low priority.

**Comment by maneesha** [comment]
Update to define priority levels:

**For online workshops:**
* High:  <= 30 days away
* Medium:   30-60 days away
* Low: >= 60 days away

**For in person workshops**
* High: <= 60 days away
* Medium: 60-90 days away
* Low:  >= 90 days away

Additionally, the admin should be able to manually override and set priority level.
After the project is fully implemented, we  may want to revisit adding additional criteria to the priority level such as number of instructors signed up/confirmed and lessons they can teach.

**Comment by pbanaszkiewicz** [comment]
@maneesha story updated, please review.

**Comment by maneesha** [comment]
Looks good. We can add a separate story when we decide on additional criteria.

**Comment by maneesha** [comment]
@pbanaszkiewicz  can we remove "stub" from this? Is there anything else you need?

**Comment by pbanaszkiewicz** [comment]
> @pbanaszkiewicz can we remove "stub" from this? Is there anything else you need?

@maneesha: I removed it.

**Comment by pbanaszkiewicz** [comment]
@maneesha should the priority set automatically change when date progresses? Ie. if we start with LOW priority will it continue to move to MEDIUM and then to HIGH?

**Comment by maneesha** [comment]
Yes, priority levels should change as the date progresses.

**Comment by pbanaszkiewicz** [comment]
@maneesha should it progress also if it's set manually?
