### ISSUE TITLE
Update AMY developer documentation

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2090]
Now that we have [user documentation](https://carpentries.github.io/amy/users_guide/) updated, I would also like to make sure we have developer documentation updated.

For example, the [Server Infrastructure page](https://carpentries.github.io/amy/design/server_infrastructure/) notes that it is hosted by the Software Carpentry Foundation on Rackspace server; has outdated information on setting up a virtual environment; says it is using a SQLite database, etc.  

I haven't done a thorough reading of all this, as I don't know the back end well enough to identify everything that should be updated.

**Comment by maneesha** [comment]
@pbanaszkiewicz @elichad  Is this now complete? If so, I'd recommend closing this issue and making sure we have a step in all our workflows to update documentation any time we have new or changed features in AMY.

**Comment by elichad** [comment]
I haven't noticed anything particularly out of date in the developer documentation so far. I'd be happy to close this unless @pbanaszkiewicz thinks there's something missing.

**Comment by maneesha** [comment]
Thanks @elichad 
@pbanaszkiewicz  can you close unless there is anything else you want to add for now?

**Comment by pbanaszkiewicz** [comment]
Let's close it since I updated infrastructure recently.
