### ISSUE TITLE
Update conditions for sending out automated emails

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2092]
Currently the logic for sending out emails is not impacted when actual dates change.  

Recommendation from @pbanaszkiewicz  is:  instead of this kind of if-else https://github.com/carpentries/amy/blob/develop/amy/workshops/views.py#L1171..L1199 we should always remove scheduled action and then only add it back if PostWorkshopAction.check(new) is true.

**Comment by pbanaszkiewicz** [comment]
@maneesha On one hand I could do a change that would recalculate email's send date, but on the other hand I believe there is a workaround: users should remove the date from workshop before setting it to a new date.

If you'd like, I can work on the change in 4.1 (we're almost feature complete) or 4.2 release.

**Comment by maneesha** [comment]
@pbanaszkiewicz if we remove the date and then add the date back in, does the condition reset?

**Comment by pbanaszkiewicz** [comment]
@maneesha yes, when you remove the date completely then the whole scheduled email should be removed. Adding the new date back in will schedule a new email at a different date.
