### ISSUE TITLE
Change criteria for sending (not sending) automated emails

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2093]
Currently we have a tag for "automated emails" and only events with this tag checked have automated emails sent out.  
We would like to change this to a "no automated emails" tag.  Then, automated emails will go out for all workshops except for when the "no automated emails" tag is applied.  

Note that automated emails should not be sent out for instructor training and bonus modules so we may need to apply additional logic here.

**Comment by pbanaszkiewicz** [comment]
Related: #1765.

**Comment by maneesha** [comment]
Closing as we have a new system to manage sending emails
