### ISSUE TITLE
Update fields for Event Tasks

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2094]
Right now, for Event Tasks we have four fields - Person, Role, Title, URL.  
We have never used the Title or URL field so these should be removed at least from the UI.  
I will leave it to @pbanaszkiewicz  to decide if there is a reason to keep them in the back end database model.

**Comment by maneesha** [comment]
@pbanaszkiewicz  I can start working on this PR if you let me know - should we change just the UI, or should we remove these fields from the model as well?

**Comment by pbanaszkiewicz** [comment]
@maneesha I don't think `title` or `URL` are used. I think you can remove them from both UI and database.

Once you remove the fields and apply the migration, you should run the tests to figure out if something broke.

Finally the database documentation should be updated to reflect removal of these fields.
