### ISSUE TITLE
Issue with Amy User Interface

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#2097]
AMY interface is acting very differently over the last few weeks. Previously, I could use TAB to switch fields or press ENTER to select a field, type text into a lookup field. This helped with searching dropdowns or multi-option fields for the appropriate option. Currently, we are unable to use these shortcuts for data entry. Here is an example:

While editing a person, and on the Awards tab:
- The "Event" & "Awarded by" fields no longer allow you to use Enter-Enter to begin typing to locate your desired option. I'm pretty sure I used to have to push enter twice, the first ENTER to open the drop-down and the second ENTER would allow me to begin typing to locate the appropriate item in the lookup field.

This is the same for the following fields:
- While editing a person, In the tasks tab: "Event", "Associated member site in TTT event"
- While editing an event, In the tasks tab: "Person"
- On Training Requests: "Training", "Membership seats"
All of these fields are the same type of lookup field.

Is there any way to correct this change? and/or can you offer any advice on how we can enter data without having to use the mouse to select the field input box? This does have impacts on our ability to enter data efficiently.

**Comment by pbanaszkiewicz** [comment]
@Talishask I have a fix for that. I'll submit it soon.

![select2_focus_on_open](https://user-images.githubusercontent.com/72821/143772053-2e5ef161-cf9d-419f-893d-400c556b9982.gif)

Once you navigate to a field like "Event", and you press `[enter]`, the menu pops up where you can type in text to search through the results. You can use arrow up/down to select a specific result and press `[enter]` to confirm it.

**Comment by Talishask** [comment]
YAY! That's exactly how I used to navigate those fields. Thank you!
