### ISSUE TITLE
Update pricing information in AMY

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2098]
Currently we have mentions of The Carpentries workshop fee of $2500 on our [request](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L2976) and [inquiry](https://github.com/carpentries/amy/blob/develop/amy/extrequests/models.py#L249) forms.  

> I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.

This text should be changed to 

> I am with a government site, university, or other nonprofit. I understand the workshop fee as listed on [The Carpentries website](https://carpentries.org/workshops/#workshop-cost) and agree to follow through on The Carpentries invoicing process.

This change should take effect anytime before January 4, 2022.  ~~I will update the link to the website shortly.~~ 

EDIT to link to the workshop cost page and update timeline.

**Comment by fmichonneau** [comment]
Given that the new text points to a link with the pricing information rather than the new pricing structure itself, this change could go live before January 4 (as long as the link is valid).
