### ISSUE TITLE
Remove auto-fill of membership benefits

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2100]
Right now, membership benefits (number of workshops and number of instructor training seats) gets automatically filled in based on membership level.  Because these benefits will change and may get customized, we would like to remove this feature and have these fields manually entered in.

**Comment by pbanaszkiewicz** [comment]
This should be fairly simple, as the required data to be entered is stored in `amy/static/membership_create.js`. I just want to make sure @maneesha this feature will not be needed again in future?

**Comment by maneesha** [comment]
Tagging @elletjies  and @ErinBecker  to confirm -- they recommended removing this feature entirely.
