### ISSUE TITLE
Consents: slug of consents terms is hard-coded

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#2118]
the following 3 slugs for consent terms: "may-contact", "public-profile", and "may-publish-name" are hardcoded and needed. If these terms are edited with new names, AMY errors. 

We need to make sure that all the views rely on the term's content when they are displayed.

**Comment by pbanaszkiewicz** [comment]
I actually think we should keep these important consent terms with unchanged names, as we may depend in the code on them. Unless it's actually reasonable to assume they will be replaced in future by other terms, then perhaps we should:

1. think of a way to mark replacement and newest version (versioning system?)
2. or ditch dependencies from the code

**Comment by pbanaszkiewicz** [comment]
Call 12/1/2022: don't allow to change consent term slug. It should be immutable.

**Comment by pbanaszkiewicz** [comment]
The solution chosen was to generate slug from term key on the fly (by replacing `-` with `_`).
