### ISSUE TITLE
Default dates for roll over memberships

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2147]
When a new membership is created by rolling over an existing membership, by default the new membership should start the day after the previous one and last for one calendar year.

For example, membership start 2021-03-01 ends on 2022-02-28.  New membership should start 2022-03-01 and end on 2023-02-28.  
This avoids overlapping dates for start/end of consecutive memberships.

**Comment by maneesha** [comment]
@pbanaszkiewicz  @elichad  is there any other information needed to implement this feature?

**Comment by elichad** [comment]
This has been fixed by #2152 .
