### ISSUE TITLE
Warning if a membership has already been rolled over

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2148]
If an admin rolls over Membership A to Membership B, and then tries to roll over Membership A again, they should get a warning noting a rolled over membership has already been created and asking them if they want to continue.

**Comment by maneesha** [comment]
@pbanaszkiewicz @elichad is there any other information needed to implement this feature?

**Comment by elichad** [comment]
The roll-over button is disabled if Membership A has already been rolled over (see https://github.com/carpentries/amy/issues/1933). Is that sufficient to close this?

**Comment by maneesha** [comment]
I think we can close this as far as the functionality of preventing rolling over a membership twice.

@elichad  if you want you can keep this open as an accessibility improvement, or consider buttons in general when we look at accessibility and close this here.
