### ISSUE TITLE
Training Request Search

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#2149]
If you search for someone's name that only has a training request and not an AMY profile, the regular search interface will not return any result in the "training request" tab. It's only possible to find this request if you search through it in the Training request view (https://amy.carpentries.org/requests/training_requests/)

reported by @sheraaronhurt

**Comment by maneesha** [comment]
Note this has to do with how the search is operating on full names for training requests.  Expected search results are returned if you enter in only the first or only the last name.

**Comment by maneesha** [comment]
Fixed with #2151
