### ISSUE TITLE
Instructor Selection: Event must have location

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2153]
To start the instructor selection process, an event must have a location.  The admin will be responsible for entering an approximate location by lat/lon (i.e., the center of the university campus) if an exact location is not yet known.

Online events must list "online" as the location.

**Comment by pbanaszkiewicz** [comment]
@maneesha do you want me to enforce these values when user is starting the selection process for a given event? (Screenshot of the form used to start the process)
![obraz](https://user-images.githubusercontent.com/72821/161843771-18376d54-9e2f-4d54-abb9-dcae87cddc91.png)
