### ISSUE TITLE
Instructor Selection: Event must be in future

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2154]
Events with start date in past should not be on the event list.

**Comment by pbanaszkiewicz** [comment]
@maneesha which list do you mean?

**Comment by maneesha** [comment]
Past workshops appear on this list: https://test-amy.carpentries.org/dashboard/instructor/teaching_opportunities/

**Comment by pbanaszkiewicz** [comment]
Note: don't display teaching opportunities (FOR INSTRUCTORS ONLY) for events that are past their start date.
