### ISSUE TITLE
Create migration to assign Instructor award to SWC, DC, and LC Instructors

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#2166]
All community members who currently have at least one of the following awards:

- SWC Instructor
- DC Instructor
- LC Instructor

need to receive the "Instructor" award.

If a community member has more than one Instructor award, they should get assigned the "Instructor" badge with an award date that corresponds to the earliest award received.

The person who assigned the original award should also be the person who is recorded as assigning the "Instructor" award.
The event associated with the original award should also be the event associated with the "Instructor" award.

The previous Instructor awards a community member has received should be kept.

See [this profile](https://amy.carpentries.org/workshops/person/5507/) as an example

**Comment by pbanaszkiewicz** [comment]
@fmichonneau I assume that "The person who assigned the original award" and "The event associated with the original award" correspond to the earliest instructor award received in case a person has more than 1 instructor awards. Can you confirm?

**Comment by fmichonneau** [comment]
yes, that's correct. Thanks!
