### ISSUE TITLE
Update view to find workshop staff

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#2168]
update this view https://amy.carpentries.org/workshops/workshop_staff/ to only use the "Instructor" (and "Trainer") awards.

**Comment by pbanaszkiewicz** [comment]
@maneesha We have many places depending on the logic for determining if a person is an instructor. Until now this logic has been: `Does the person have any of the badges: swc-instructor, dc-instructor, or lc-instructor?`.
If I changed the logic to `Does the person have a badge instructor, and an active Instructor Community Role` then this logic (and underlying query) becomes quite complex.

I propose to use `Does the person have an active Instructor Community Role`, which should be simple enough.

**Comment by maneesha** [comment]
Because the Instructor role requires an Instructor badge, this condition should work.
