### ISSUE TITLE
update views to only show "Instructor" award instead of individual lesson program Instructor awards

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#2170]
There are several views that display the different individual lesson program Instructor awards that someone might have, for example:

![Screenshot from 2022-04-26 10-39-53](https://user-images.githubusercontent.com/5502922/165325956-47589b4b-675e-4f7b-96e5-d022d626fa0a.png)

update these views to only display the unified "Instructor" award instead.

**Comment by maneesha** [comment]
We should have an  indicator for the badge and also have an indicator for an active community role.

**Comment by pbanaszkiewicz** [comment]
@maneesha this is how indicator for instructor badge as well as for an active instructor community role looks like:
![obraz](https://user-images.githubusercontent.com/72821/181371531-df682438-0eb1-4ccd-b804-601a6f677bd6.png)

Do you accept this look?
