### ISSUE TITLE
Community Roles: Allow auto-assignment of community roles

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2194]
In the community roles config - if a role requires a badge, we should also be able to note whether that role should automatically be assigned when that badge is awarded.

**Comment by pbanaszkiewicz** [comment]
@maneesha This task only describes the need to note whether role should be linked when badge is awarded. This means there will be another ticket for actually implementing the auto-assignment, correct?

**Comment by maneesha** [comment]
@pbanaszkiewicz I had thought of that all together in one.  
I'll create a new issue.
