### ISSUE TITLE
Instructor Selection: Event listing headers for Instructor view 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2200]
The current header for the Instructor view is 
> (slug) at (venue)

Instead we would like to see 

>  (Lesson Program/Curriculum) at (Host Site) on (dates)

**Comment by pbanaszkiewicz** [comment]
@maneesha by lesson program do you mean for example "Data Carpentry: Genomics"? Or do you mean something else?
For Host Site we don't currently store anything related to site on Host (Organization) model, do you perhaps mean just the Host name?

**Comment by maneesha** [comment]
Yes - this is exactly right. Thank you!
