### ISSUE TITLE
Hide lesson program specific checkout steps

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2215]
Now that we have a single Instructor badge, we do not want to see the lesson program specific checkout steps. These should be hidden from view so only four options remain.

- ~DC Demo~
- ~DC Homework~
- Demo
- Discussion
- Homework
- ~LC Demo~
- ~LC Homework~
- ~SWC Demo~
- ~SWC Homework~
- Training

**Comment by maneesha** [comment]
I don't know which of the following may be a better option:

1. Add a 'visibility' condition to each of the checkout steps.
2. Remove the unused checkout steps entirely and run a migration/update to make anyone who had the lesson program specific step assigned to them now have the generic step assigned to them.

@pbanaszkiewicz  in 2023 we may be considering larger changes to the checkout process. Much of that is currently unknown but we may want to keep this in mind as we consider which of these two things to do.

**Comment by pbanaszkiewicz** [comment]
@maneesha did you check the test server? I think only 4 checkout steps are visible now, however we still support the crossed-out ones (e.g. DC Demo) as there was no migration for old entries.

**Comment by maneesha** [comment]
We do still see all the options when creating a new training progress record.

![image](https://user-images.githubusercontent.com/829690/187659567-82688209-35db-4176-a2fc-d75611ecee58.png)

**Comment by pbanaszkiewicz** [comment]
@maneesha I merged a small bugfix which hides the unused checkout steps in the form that you mentioned in https://github.com/carpentries/amy/issues/2215#issuecomment-1232765617. Please check on the test server and if it doesn't work as you wish - reopen this ticket.
