### ISSUE TITLE
AWS Lambda functions using Node.js

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2235]
Not sure if this goes here... Putting it here since it seems to be AMY related.   @pbanaszkiewicz  please let me know what we should do.

We got an alert from AWS, excerpted here:

> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
> 
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
> 
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.
> 
> The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Node.js 12. To find all such functions in your account, repeat this command for each region:
> 
> `aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='nodejs12.x'].FunctionArn"`

Running that command returns:
`arn:aws:lambda:us-east-1:860325783027:function:redirect-to-amy:$LATEST`

**Comment by pbanaszkiewicz** [comment]
@maneesha I think the lambda can be removed. All it is doing is redirecting to AMY, but it looks like this function is not triggered by anything, and there are no logs or metrics available, which means recently it has not been run.

It was created 3 years ago, and I don't remember this, so it may have not been me.

Do you want me to remove it for you?

**Comment by maneesha** [comment]
Yes, can you remove this? Thanks!

**Comment by pbanaszkiewicz** [comment]
@maneesha I removed the lambda.
