### ISSUE TITLE
Invalid link to an award in community roles table

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2240]
https://amy.carpentries.org/workshops/person/464/edit/#communityroles community roles table doesn't have a valid link to an award.

**Comment by maneesha** [comment]
@pbanaszkiewicz  in the link you shared, you are in the edit screen to add a role to your own record.  An `Instructor` role already displays.  Can you clarify what you are trying to do?

**Comment by pbanaszkiewicz** [comment]
Fixed via #2248.
