### ISSUE TITLE
Error: Deleting an award that is required by a community role

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2243]
On the real AMY, this returns a 500 Server Error.

I tried this on the test server (where it looks like `DEBUG=True`) and get an `AttributeError` - `'Award' object has no attribute 'get_absolute_url'` as well as `ProtectedError` as the Award has a protected foreign key in CommunityRole.

**Comment by pbanaszkiewicz** [comment]
@maneesha do you want a bugfix release (like v4.0.1) pretty soon, or is v4.1 good enough?
