### ISSUE TITLE
Improving accessibility: Time zone conversion for workshops

### ISSUE THREAD

**Issue by annajiat** [carpentries/amy#2252]
Currently, timezones are part of the notes and are written like
9:00 am-5:00 pm Eastern Time
1:00 pm-5:00 pm Greenwich Mean Time
12:30-5:30pm Pacific Time

It may not be very accessible and UTC timing is not mentioned. 
In the previous instructor signup spreadsheet, we used to have additional link besides text like the above e.g., 
[see in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=University+of+Idaho&iso=20221031T09&p1=3993) 

We might need **two** changes:
a) improving the format so that UTC timing always mentioned in addition to the local time in both emails and AMY.
b) link to convert to viewer's time zone.

Would it be possible to add some links to see the timings in UTC and  local time if it was mentioned for every mention of a start time?
It may be possible to do so using regex and then generating URL parameters based on that to view the time in another timezone.

**Relevant discussions:**
1)
[Feedback collected regarding accessibility #29](https://github.com/carpentries/community-facilitators-program/issues/29)
carpentries/community-facilitators-program/issues/29

2)
[Mentioning UTC times in email and workshop website #36](https://github.com/carpentries/community-facilitators-program/issues/36)
carpentries/community-facilitators-program/issues/36

**Comment by maneesha** [comment]
We will be adding timeanddate links to the description of all online events.  Additional time zone features will be addressed in https://github.com/carpentries/amy/issues/2255 so I am closing the issue here.
