### ISSUE TITLE
countries listed as filter options for instructor recruitment

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2254]
In the instructor view, currently these five options show up as filter options.  Why are these five countries listed?  They do not represent countries that have active recruitment processes open.

![image](https://user-images.githubusercontent.com/829690/198036229-1478d7f0-1d62-4e66-8c7d-6a4ad2299f3e.png)

**Comment by annajiat** [comment]
Should we rename "Event country" to “Region” and move it down
and add a new field to actually represent the countries?

**Comment by maneesha** [comment]
The `country` field in the database represents actual countries, not regions.  The error is in how they are retrieved to build this drop down menu.

**Comment by maneesha** [comment]
This should be resolved so that only countries with active open recruitment processes are listed.
