### ISSUE TITLE
Remove unused management commands

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2285]
* https://github.com/carpentries/amy/blob/develop/amy/workshops/management/commands/check_certificates.py
* https://github.com/carpentries/amy/blob/develop/amy/workshops/management/commands/check_for_workshop_websites_updates.py
* https://github.com/carpentries/amy/blob/develop/amy/workshops/management/commands/instructors_activity.py (probably will be removed with #2272)
* https://github.com/carpentries/amy/blob/develop/amy/workshops/management/commands/sync_usersocialauth.py

**Comment by pbanaszkiewicz** [comment]
@maneesha Can you confirm that neither of these commands are regularly used?

**Comment by pbanaszkiewicz** [comment]
@maneesha ping

**Comment by maneesha** [comment]
I have never used any of these commands
