### ISSUE TITLE
Consents: remove old consents (`Person.data_privacy_agreement`, `Person.lesson_publication_consent`, `Person.may_contact`, `Person.publish_profile`)

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2293]
There's a number of difficulties when removing these parameters.

1. Some queries depend on these fields
2. These fields are involved in person merging

Code analysis follows.

- [x] Remove the fields from `Person`
- [x] `api.filters.filter_consent` should probably be updated as it has a bunch on unnecessary if statements.
- [x] `api.tests.test_filter.TestFilter.setUp` try to understand why `get_option`, `get_consent`, `Consent.reconsent` are needed and if a simpler approach wouldn't be better
- [x] `autoemails.actions.NewInstructorAction.check` doesn't depend on `may_contact`, but it has some tests about this behaviour (`TestNewInstructorAction.testCheckForNonContactablePerson`, the same in `NewSupportingInstructorAction`: `TestNewSupportingInstructorAction.testCheckForNonContactablePerson`)
- [x] `TestTermsMiddleware.test_old_terms_do_not_affect_terms_middleware` probably isn't needed anymore
- [x] when matching existing person to a training request, in `extrequests.views._match_training_request_to_person`, person is assigned `may_contact` and `data_privacy_agreement` -> **Should we do that?** Probably up for discussion with Maneesha
- [x] related tests: `extrequests.tests.test_training_request.TestMatchingTrainingRequestAndDetailedView.test_matching_with_existing_account_works` and `extrequests.tests.test_training_request.TestMatchingTrainingRequestAndDetailedView.test_matching_with_new_account_works`
- [x] tasks for workshops with issues are filtered by people who agreed to contact, `reports.views.workshop_issues`
- [x] `templates/dashboard/instructor_dashboard.html` contains some old-style consents
- [x] person email is displayed in all tasks page only if they agreed to may contact consent, `templates/workshops/all_tasks.html`
- [x] person email is displayed in badge details page only if they agreed to may contact consent, `templates/workshops/badge.html`
- [x] person email is displayed in event edit page only if they agreed to may contact consent, `templates/workshops/event_edit_form.html`
- [x] person email is displayed in event details page only if they agreed to may contact consent, `templates/workshops/event.html`
- [x] person email is displayed in Find Workshop Staff page only if they agreed to may contact consent, `templates/workshops/workshop_staff.html`
- [x] event contacts filter on people who agreed to may contact consent, `workshops.models.Event.contacts`
- [x] old-style consents are used in person archival, `workshops.models.Person.archive`
- [x] `TestArchivePerson` contain old-styled consents
- [x] person merging `workshops.views.persons_merge`
- [x] `TestPersonMerging` contain old-styled consents
- [x] details of event contain list of tasks filtered by person's old style may-contact consent, `workshops.views.event_details`
- [x] all emails on event details page filter by person's old style may-contact consent, `workshops.views.event_details`
- [x] `fake_database.py` script stores `may_contact` and `publish_profile` with a random value when creating entries
- [x] Revert changes in `fake_consents` (`amy/workshops/management/commands/fake_database.pyL861`)

**Comment by maneesha** [comment]
> when matching existing person to a training request, in extrequests.views._match_training_request_to_person, person is assigned may_contact and data_privacy_agreement -> Should we do that? Probably up for discussion with Maneesha

The data privacy field should be carried over from their training request.  

For the "may contact" - this is something I began discussing with our previous Director of Technology and will revisit with our new DoT.  We thought that "may contact" should be required for necessary communications (privacy policy updates, profile archival, etc.) but users can opt out of other types of communication.  We will discuss this more after they start.
