### ISSUE TITLE
Issue: "Projects" navigation menu item auto expanded

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2299]
Split from #2290.

> Additionally the users guide should open with the index page and no menus expanded (currently the Projects menu is expanded when you to to https://carpentries.github.io/amy/)

More details, and possible upstream bug: https://github.com/carpentries/amy/issues/2290#issuecomment-1328047890

**Comment by maneesha** [comment]
We can also consider a different theme altogether.  I just tried [this theme](https://github.com/squidfunk/mkdocs-material) locally and it looks good.  I also like that it appears to be actively maintained.

**Comment by pbanaszkiewicz** [comment]
@maneesha I like this idea a lot.
