### ISSUE TITLE
Make "Agreement document" required field in membership model

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2307]
At the Membership team meeting today, we discussed that the field for "Agreement Document" should be a required field.  Keeping this issue open to note other changes to fields in the membership model we should make.  

Tagging @elletjies  FYI, please feel free to add anything else here

**Comment by maneesha** [comment]
I haven't seen any other response from @elletjies so I think this should be it for now.  Note we are considering other changes to membership separately (including the enforcement of registration codes and changes to pricing for in-person/online workshops).  

@pbanaszkiewicz @elichad is there any other information needed to implement this feature?

**Comment by elletjies** [comment]
@maneesha I missed this. I think this is all for now.
