### ISSUE TITLE
Remove question about learner count from workshop request form

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2308]
Following conversation with @danielle06 we would like to completely remove the question on the workshop request and inquiry forms about "Anticipated number of attendees."

**Comment by maneesha** [comment]
@pbanaszkiewicz @elichad is there any other information needed to implement this feature?

**Comment by pbanaszkiewicz** [comment]
@maneesha do you want to keep it for older entries, or do you not care about existing data for this field?

**Comment by maneesha** [comment]
@sheraaronhurt  @danielle06  Can you take a look at the issue above? When we remove the question about how many learners from the WRF, is it ok to delete the historical data associated with it? Would you ever want to go back and get it?

**Comment by sheraaronhurt** [comment]
@maneesha I don't think we will need it. We were not doing anything with it previously.
