### ISSUE TITLE
Link to pre/post workshop results in Workshop activity list

### ISSUE THREAD

**Issue by sstevens2** [carpentries/amy#2312]
I was discussing my struggle with finding the pre/post workshop survey results by searching through my emails for the links with a colleague and was wondering if it would be possible to have that link as a column in the workshop activity table that is part of the your profile page?

**Comment by maneesha** [comment]
Thanks for bringing this up @sstevens2  
I think this is addressed in #2016 so I am closing this here.  Please feel free to re-open or create a new issue if there is anything else you want to see.

**Comment by sstevens2** [comment]
Sorry I missed the other Issue @maneesha! Thanks for sending me there!
