### ISSUE TITLE
Different colour scheme for test-amy / local builds

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2322]
It'd be useful to have a visual indicator of which site you're on - it's currently quite easy to mix up production AMY and staging/local AMY pages if you have both open.

I think the nav background colour would be the easiest and most visually obvious thing to change.

**Comment by maneesha** [comment]
Thanks for opening this issue @elichad 
In the interest of accessiblity and to make it clear what the different color means, we may also want to add a non-color cue. Perhaps an additional div in the navbar as a reminder that you are in the testing environment? 

I am not at all bound to these colors or text; just an example of what I was thinking of:

![image](https://user-images.githubusercontent.com/829690/215091801-3150797e-42e7-4561-958a-664e557e5e18.png)

This would require some conditional in the build process (i.e., ```if local or test then css....```)

**Comment by pbanaszkiewicz** [comment]
Good idea!

**Comment by maneesha** [comment]
Update to say this should also apply to the login screen, so it is clear to users whether they are logging in to the test version or the real version.
