### ISSUE TITLE
Display consents in person merge view

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2370]
When merging two Persons, their consents don't display correctly in the merge view (but are still merged). We could copy what has been written for the training requests merge view: 
https://github.com/carpentries/amy/pull/2363/files#diff-28b075b2b3e469ffbc4023daeb7f657ce17236f815f3aebfe1f64c8783d2d60cR955
https://github.com/carpentries/amy/pull/2363/files#diff-db895696b527b478871dcb468a1b1d3a896d565667ab30f6e1cf1a9150c18783R234

**Comment by pbanaszkiewicz** [comment]
Also remove "Combine" option from person merging for consents
