### ISSUE TITLE
Test-amy2: update login through github

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2372]
It's still set up for test-amy.

**Comment by pbanaszkiewicz** [comment]
@maneesha @froggleston I believe the OAuth application entry was transferred from my account over to Carpentries. I cannot manage it myself.

You should be able to find it here:
https://github.com/settings/developers

![obraz](https://user-images.githubusercontent.com/72821/230647388-548d9ba8-c1ff-4543-bb87-bcd272eea134.png)

It's enough to update OAuth application domain to test-amy2, but if it changes the authorization token(s) please let me know.

**Comment by froggleston** [comment]
Hey @pbanaszkiewicz - do you have the configuration for the old app that I can work from? DM me in slack if there's sensitive info.

**Comment by pbanaszkiewicz** [comment]
@froggleston Did we resolve this issue or not? I don't remember.
