### ISSUE TITLE
Update workshop request form: Warning to admin that workshop may not be allowed 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2393]
We have a separate issue to validate member codes in the workshop request form  (#2380).

Once this feature is implemented, we should be able to add in another level of validation for the admin who may be accepting the workshop request.  If the workshop requested exceeds the workshops allowed (online or inperson), the admin should get a warning before being able to accept that workshop request and create a new event.

**Comment by elichad** [comment]
Closed by #2553 which added this info to the workshop request details page.
