### ISSUE TITLE
Add a filter to the workshop request view to filter for requests with invalid member codes.

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2398]
This can happen after #2380 is implemented.  
The view for workshop [requests](https://amy.carpentries.org/requests/workshop_requests/), [inquiries](https://amy.carpentries.org/requests/workshop_inquiries/), and [self organized submissions](https://amy.carpentries.org/requests/selforganised_submissions/) should all include an option to filter by invalid member registration codes.
We should be able to edit this field just as we can edit other fields in those forms.

**Comment by elichad** [comment]
Closing this as won't complete, for two reasons:
1. the hard validation on the WRF reduces the need for this filter
2. I've added the important membership info directly to the WR details page as part of #2553, so it will be readily visible as the team processes requests.
