### ISSUE TITLE
Remove the "Evaluated by" field 

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2407]
Each trainee progress step has a field for "Evaluated by"
I think this just becomes the person who did the data entry.  If it is not used in any way, we should remove it.  
Assiging to https://app.asana.com/0/412899495476717/list to decide if she wants to see this data.

Created automatically from an Asana task.

**Comment by maneesha** [comment]
Yes, you're right that it is just the person who did the data entry. We do not need to keep this data.

**Comment by maneesha** [comment]
@elichad can you verify that this hover displays correctly with this field removed? 
![image](https://github.com/carpentries/amy/assets/829690/d441bb90-e822-43c8-b60a-142a05080928)
(the "evaluated by" line should be gone entirely)

**Comment by elichad** [comment]
Yes, that line is removed (the possible 'Discarded' text in the hover is also removed with the removal of the `discarded` field). Screenshot from my working branch for the checkout feature
![Welcome Session training progress with hover text: Passed Welcome Session on Thursday April 20 2023 at 10:27. Click to edit or delete.](https://github.com/carpentries/amy/assets/20683271/5270f604-9261-4775-bb80-0347b61b2b46)
