### ISSUE TITLE
Person search doesn't work for personal or family names which contain spaces

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2415]
For a user with personal "X Y" and family "Z", or personal "X" and family "Y Z", searching "X Y Z" will not return the person. Searching just "X Z" will return the person.

**Comment by maneesha** [comment]
I remember a similar issue coming up before and I can't find it now. Maybe it was something I just talked with @pbanaszkiewicz about but never opened an issue? @pbanaszkiewicz  do you remember?

**Comment by maneesha** [comment]
Issue Training Request Search #2149 and related PR Training search #2151 are probably what I was thinking of.  As noted in that PR, that PR introduced some redundant code.  It may be useful to refactor those queries while addressing this issue.

**Comment by sheraaronhurt** [comment]
Cant wait to see this one fixed :)
