### ISSUE TITLE
Error in entering trainee demo session

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2474]
When an admin tries to enter the trainee demo session, we get this error:

![screenshot of error in demo submission](https://github.com/carpentries/amy/assets/829690/b535dc62-1570-41cb-8a20-e4c303ae4c84)

**Comment by maneesha** [comment]
Note that I want to test this view for [trainees eligible for certification](https://test-amy2.carpentries.org/trainings/trainees/?search=&is_instructor=eligible&training=&training_request=unknown&order_by=) but can not as this bug prevents creating eligible trainees.

**Comment by elichad** [comment]
The 'Demo' requirement was misconfigured in test-amy to require a URL when it shouldn't - I've updated that through the admin panel, so this should work now. On the real AMY and in our seeding scripts it is configured correctly.

**Comment by maneesha** [comment]
Thanks @elichad 
I always forget what data is hardcoded and what is in the admin panel.
