### ISSUE TITLE
Update information at top of training page

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2475]
At the top of the [training progress page](https://test-amy2.carpentries.org/dashboard/instructor/training_progress/) the trainee should see the following information.

* Remove the warning "Due to the structure of our checkout tracking progress, all steps towards checkout may not be included here. If your instructor badge is correctly displayed, you are in good standing." 
* If the Instructor badge has been awarded, keep that part as is
* If the Instructor badge has not been awarded but all three steps are complete, text should say "Congratulations. You have successfully completed all steps towards Instructor certification. You will receive you certificate and more information by email in 7-10 days."
* If training is complete but all three steps have not been completed, text should say "Please review your progress towards Instructor certification below.  As a reminder, because you completed training on [DATE], you have until [DATE + 90 days] to complete these requirements.  Visit our [checkout page](https://carpentries.github.io/instructor-training/checkout)  for more information.  If you would like an extension on this deadline, please contact us at [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org) If you have recently completed a training or step towards checkout, please allow 7-10 days for this information to show up in your profile."

(edit to add link to checkout page)

**Comment by karenword** [comment]
Can I suggest a change to the last item:

> Please review your progress towards Instructor certification below. As a reminder, because you completed training on [DATE], you have until [DATE + 90 days] to complete these requirements. Visit our [checkout page](https://carpentries.github.io/instructor-training/checkout) for more information. If you would like an extension on this deadline, please contact us at [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org) If you have recently completed a training or step towards checkout, please allow 7-10 days for this information to show up in your profile.

instead: 
Please review your progress towards Instructor certification below. Based on your training date of [DATE], the 90-day deadline to complete these requirements is [DATE + 90 days]. If you would like an extension, please contact us at [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org) and refer to your confirmation email for your updated deadline. If you recently completed a training or checkout step, please allow 7-10 days for this information to show up in your profile. Visit our [checkout page](https://carpentries.github.io/instructor-training/checkout) for more information.


This will more appropriately signal to trainees that the indicated deadline will not be updated in the message after they have been granted an extension. (Other language edits suggested but not essential to that primary goal.)

**Comment by karenword** [comment]
Also note typo "you certificate" -> "your certificate" in bullet 2

**Comment by maneesha** [comment]
Thanks @karenword  that sounds good to me.
