### ISSUE TITLE
Admin can add multiple signups for the same Instructor at the same workshop

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2495]
An Instructor can only sign up to help at a workshop once. However, an admin can add more signups for that same Instructor. This has potential to create confusion if the states are changed for both signups.

Trying to confirm both causes a database error (#2449), but accepting one and declining the other means different emails will be sent and different status will be shown to the Instructor depending on the order of those actions. 

The correct action would be to delete the duplicate, but we should make it harder to run into this problem in the first place.

![Screenshot of a fake event recruitment, with two signups for the same Instructor, Marcus Aguirre.](https://github.com/carpentries/amy/assets/20683271/d6183744-cbc0-4ee9-b81a-576abfa79ce8)

**Comment by maneesha** [comment]
Thanks for catching this @elichad. I agree that the fix should be to prevent the admin from creating duplicate signups.

**Comment by maneesha** [comment]
Some other questions/notes:

* In addition to different emails being sent out if the admin accepts one and declines the other, what happens to the instructor task that gets created?  
* Can an admin create a signup if the Instructor has already created their own signup? If so, this should be prevented as well. 
* If the signup was created by the admin and not the instructor, can we have some way of indicating that in the view?

**Comment by maneesha** [comment]
> If the signup was created by the admin and not the instructor, can we have some way of indicating that in the view?

Eli: Not sure if we track who creates the signup.  Could have admin add this to notes (but relies on the human)

**Comment by maneesha** [comment]
Eli: This should be relatively easy to do, with a unique constraint or a check when signup is created.
