### ISSUE TITLE
Error when "Ask to Repeat" due to non-Carpentries repo

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2507]
See this trainee as an example: https://test-amy2.carpentries.org/workshops/person/74/
They have one "Get Involved" step that is to a non-Carpentries repo.  When the admin tries to mark that as "Ask to Repeat" they get an error that it is a non-Carpentries repo. 
We want the admin to be able to mark this as "Ask to repeat" so that the trainee can go back and make the appropriate changes.

**Comment by elichad** [comment]
Thanks for catching this @maneesha! There are a few ways we can approach this:

1. disable this specific check on the admin side of the training progress form, so it's only applied on the trainee side
2. disable this specific check on progress created before the rollout
3. try to assess all outstanding progress by the end of Friday, and hope nothing comes in with an invalid URL before the deployment on Saturday

I favour option 1 as it's straightforward to implement and test (unlike option 2) and will allow us to edit older progress if needed in future (unlike option 3). The downside is that an admin could then enter an invalid URL - but as we aren't expecting admins to create many of these entries themselves, and they're also well informed about what is accepted for this step, I think that's okay. What do you think?

Note that this bug in its current state would not affect the data migration, as this validation is not called during migrations.

**Comment by maneesha** [comment]
Option 1 sounds good to me.
