### ISSUE TITLE
Feature flags: create a process for ensuring flags are enabled or disabled in production

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#2524]
Current solution allows users to toggle feature flags. This works fine for development and testing environments, but may not be desired for production environment.

@maneesha @froggleston Please consider if you want to allow users in production (admins or instructors) to change their feature flags as desired.

If we shouldn't allow users to change their feature flags in production, but instead control them ourselves, then I propose to create a process of managing feature flags after every production release. It's possible to globally enable or globally disable a feature flag for everyone without changing code through django-admin panel. It was discussed by me and @elichad here: https://github.com/carpentries/amy/pull/2516#discussion_r1301552547

Original thread: https://github.com/carpentries/amy/pull/2516#discussion_r1301488470

Current UI used for switching feature flags on and off: https://test-amy2.carpentries.org/dashboard/admin/feature_flags/

**Comment by maneesha** [comment]
I can't think of a reason we'd want to use feature flags in production.  Our current need for them is so that we can test features that are being developed in parallel.
