### ISSUE TITLE
Text about costs for corporate/for-profit workshops

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2582]
Instead of saying the costs for corporate/for-profit workshops are four times the cost for other workshops, say only that they are "higher than" the cost for other workshops. This will help maintain consistency if we ever change this. The link to workshop costs page will be the only place for current and accurate information.

Tagging @Talishask  and @sheraaronhurt  for feedback. 

![image](https://github.com/carpentries/amy/assets/829690/ef87032b-71a3-4677-bb98-d1a3a8158b3a)

**Comment by sheraaronhurt** [comment]
@maneesha I like that approach and the rationale behind it.
