### ISSUE TITLE
Remove named social media platforms from "How did you hear..." question

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2587]
On the [workshop request form](https://amy.carpentries.org/forms/request_workshop/), the question `How did you hear about The Carpentries?` includes the option `Saw The Carpentries on social media (Twitter, Facebook, etc.)`.  The two examples of social media are ones that we no longer use.  I recommend not giving any examples of social media platforms and just say `Saw The Carpentries on social media` so this form stays current regardless of our social media strategies.

Tagging @acrall  for feedback.

![image](https://github.com/carpentries/amy/assets/829690/e747fc8a-ce4e-4a0c-af7b-c8b456f1e9a9)

**Comment by acrall** [comment]
@maneesha Agree. I would remove the examples. We should also remove ableist language in this, "saw" and "heard". So change to "how did you find out about The Carpentries?" Might need additional discussion on how to modify the checklist, but "Saw the website for carpentries.org..." could be modified to "Organisational website (carpentries.org, ...). "heard about The Carpentries at a conference..." could be changed to "Learned about The Carpentries at a conference...." and "Learned about The Carpentries from a funding organisation..."

**Comment by maneesha** [comment]
To address the ableist language, we can remove verbs entirely. Also, "The Carpentries" probably does not need to be in each line - that seems redundant.

- Received an email or saw a flyer
- From a newsletter or on university website
- From the website for [carpentries.org](https://carpentries.org/), [datacarpentry.org](https://datacarpentry.org/), [librarycarpentry.org](https://librarycarpentry.org/), or [software-carpentry.org](https://software-carpentry.org/)
- From my advisor or supervisor 
- From a friend or colleague
- From social media
- At a conference, meeting, or seminar
- From a funding organization or program office
- I am already a part of The Carpentries community

**Comment by acrall** [comment]
I like that list, @maneesha. Thanks!
