### ISSUE TITLE
Make clear that registration code is required

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2590]
The question in the instructor training application notes "If you have been given a registration code through a Carpentries member site or for a specific scheduled event, please enter it here:"

As this code is mandatory, saying "if" is not correct.  Update this text to read:
"Enter the registration code you were given through your member contact or training organiser."

Tagging @karenword  for feedback. 

![image](https://github.com/carpentries/amy/assets/829690/aa6c876d-16e3-4f73-b75b-f21e5f402ad8)

**Comment by karenword** [comment]
Thanks @maneesha -- I agree. Since this only appears under "profile creation for pre-approved trainees" and this field is mandatory to select that option, the instruction should not be conditional.

**Comment by maneesha** [comment]
Closing this as irrelevant now that we have made other changes to the training form.
