### ISSUE TITLE
Remove option for open training application

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2617]
We are no longer running the open training application so we should remove this option from AMY.

This includes:

- [ ] remove text about open training at top of form (amy/templates/forms/trainingrequest.html)
- [ ] remove open training info from form submission email (amy/templates/mailing/training_request.html and amy/templates/mailing/training_request.txt)
- [ ] fix UI at top of form to only have "Profile Creation" as an option (so no accordion expanding needed - should be expanded by default; "Application type" text is no longer needed; radio button is not needed)  

We could also remove the `review_process` field from the `TrainingRequest` model. However, keeping it in may make it easier if we decide to go back to having different types of training applications.

**Comment by maneesha** [comment]
@pbanaszkiewicz suggests a rework of the accordion.  Instead of application type, we only have the registration code/url display.  On the back end, we can still have the options, but have them hidden.

**Comment by pbanaszkiewicz** [comment]
Suggested release: sooner than 4.3
