### ISSUE TITLE
Scheduled email view should include email-specific information

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2638]
In the current scheduled email view ([list view](https://test-amy2.carpentries.org/emails/scheduled_emails/) and [sample item view](https://test-amy2.carpentries.org/emails/scheduled_email/463f6747-e9a7-4665-b0ba-e13d7eb2b97a/) we do not easily see details about what email that is, especially as the template variables do not render.

@pbanaszkiewicz  Can you advise what options we have so we can tell exactly what email that is? Depending on the email, this may mean displaying the event slug, person name, award, etc.  One option may be for the scheduled email list, to include the related object in that table.  The ID currently displayed in the scheduled emails table view is not relevant to the end user so that space could be used for this instead.    Then for the item view, to move the related object (currently at the bottom of the view) to the top to make it more prominent.

**Comment by pbanaszkiewicz** [comment]
@maneesha 

Proposal for the scheduled email list:

<img width="1800" alt="image" src="https://github.com/carpentries/amy/assets/72821/fe48031b-5213-4abe-8ba3-4475498a8830">


Proposal for the details of scheduled email:

<img width="1800" alt="image" src="https://github.com/carpentries/amy/assets/72821/61093e8c-b415-41aa-b2bc-5d4c3bbfd212">


What do you think?

I made sure that all currently related objects can be linked (Instructor Recruitment Signup leads to Instructor Recruitment details, Award leads to Person details, and Event, Person and Membership lead to their detail pages).

**Comment by maneesha** [comment]
The list view looks good.
The detail view is also good - with a question about the id.  Is there a reason the human user would ever need to see this?  If not, I would hide it completely.  If it can be useful (for example in troubleshooting) then I would move it to the bottom.

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm going to move "ID" row in scheduled email details to the bottom of that table.

In regards to the notifications I mentioned during our meeting today. After merging a person this is the notification message we receive:
<img width="2560" alt="image" src="https://github.com/carpentries/amy/assets/72821/0440a940-fce8-4e03-9942-c41c973e99c8">

I'm going to change it to:
<img width="2547" alt="image" src="https://github.com/carpentries/amy/assets/72821/3f1dd388-30d4-46ce-b9fd-91e5ff4f490c">
