### ISSUE TITLE
Membership onboarding email should be for new and rollover memberships

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2662]
The email template for [New / renewing membership starting (member onboarding)](https://test-amy2.carpentries.org/emails/template/4e737df8-d2ef-4ebd-9a26-087212af233b/) seems to work for creating entirely new membership but does not trigger for rollover (renewing) memberships.

**Comment by pbanaszkiewicz** [comment]
@maneesha Is this still occuring?

**Comment by pbanaszkiewicz** [comment]
@pbanaszkiewicz To double-check - doesn't seem to be fixed in the code.

**Comment by pbanaszkiewicz** [comment]
@maneesha I looked into this. There was no code to trigger the email, and when I temporarily added such code, then I found out that there was additional safety-check for the email conditions (the membership must not be rolled over from another membership).

I also checked our documents and I believe row 9 in "sample AMY automated emails" describes membership onboarding email. It explicitly calls out "no earlier membership exists" in the conditions column.

All things considered, I will not change any code at this moment and will move this ticket to v4.4. Please let me know how do you want to proceed.
