### ISSUE TITLE
Attendance count needs to be more than just one number

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#514]
To accurately track and assess our impact, I'd like to have more than just one number to reflect attendance count.  I've gotten a few reports back where attendance on day 2 was lower than attendance day 1 -- sometimes by just a couple of people, sometimes significantly lower.  Actual attendance is also often lower than registered attendance especially for free workshops.

This speaks to a larger need to assess SWC's impact & effectiveness but to do so we need to track this data.

Something like counts for `registered`, `attendance_day_1`, and `attendance_day_2` may work as most workshops are just two days, but some are spread out over three, and instructor training may be over a few weeks.  Maybe `registered`, `attendance_day_1`, and `attendance_day_n`?

**Comment by pbanaszkiewicz** [comment]
This is another reason why I'm missing PostgreSQL. With it we would have an option to store a list (array) of attendance figures within one field.

@gvwilson any thoughts on switching?

**Comment by gvwilson** [comment]
I think we should defer switching to multi-valued attendance figures until we know that people will actually provide them - if admins start asking now, and archive answers (e.g. in a Google doc) for 2-3 months, and we see that we're actually getting data, then it's worth complicating things.  If they don't give us data, then there's no point.

**Comment by maneesha** [comment]
Sounds good @gvwilson

**Comment by shubhsingh594** [comment]
We could use a JSON object to store an array list, and then convert it into a String to store it into the SQLite database. This way we can use one field to store the attendance for all the days of the workshop individually.

**Comment by pbanaszkiewicz** [comment]
@shubhsingh594 technical solution is not an issue – having people send us the data for specific days is one.

**Comment by maneesha** [comment]
I've been tracking this & have put it in a [github repo] (https://github.com/swcarpentry/workshop_documents/blob/master/counts_by_day.csv).  We've gotten attendance by day for 30 workshops in eight months without even trying.  I think this shows us it's worth it for us to more explicitly ask instructors/hosts for attendance broken down like this and track it in AMY.

**Comment by maneesha** [comment]
@sheraaronhurt   @Talishask   How important is it that we track retention/attrition?  Do we want to know if attendance count changed over the event?  Is it more important for DC, where curriculum is continuous vs SWC where it's more modular?  Will having this data tell us if the two day model is effective? Can we compare it to workshops that are spread out over days/weeks?  Will instructors/hosts  share this data?

We have this scale in place to prioritize things.  Since this isn't a well defined fix yet, I'd suggest option 3.  Let me know what you think.

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by Talishask** [comment]
3 - I think we are still thinking about how we want to collect attendance and what information we want. I believe this is a part of a larger conversation among SherAaron, Kari & Tracy.

**Comment by sheraaronhurt** [comment]
agreed. 3

**Comment by kariljordan** [comment]
I am in agreement with 3 as well. If we collect and track this data, we are not in a position to take action or use the information to inform changes in curriculum or workshop administration.

**Comment by maneesha** [comment]
Closing this here. We will open new issues once we decide how we want to track attendance.
