### ISSUE TITLE
Database: clear migrations, move data migrations → fixtures

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#626]
We have a number of data migrations that input new values into empty database. Try creating a fresh new database:

``` shell
$ rm db.sqlite3
$ ./manage.py migrate
$ make superuser
$ make serve
```

Now log in with `admin:admin` credentials and go to http://127.0.0.1:8000/workshops/admin/ to see some of the values that we add with migrations.

Since we're switching to fake-generated "fixtures" (see #534 for details), I'd like also to get rid of all migrations that provide initial values for some of the models, and instead use fixtures for that.

I think we can safely use fixtures because these initial values don't change so often.

Also, I think removing all migrations (or squashing them while dropping data migrations) needs to be done carefully. It may require a release solely for this change (so that no new migrations are added).

**Comment by pbanaszkiewicz** [comment]
I'm deferring this for now, because with Django 1.9 the migrations are **so fast** it doesn't matter… It would still be a nice thing, but for now it's just fine.

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz I am starting to reconsider this proposal as we progress towards adding PyData specific objects to the database.
Having fixtures would make our tests independent of the initial data we intend to populate our database with.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 there are advantages to using fixtures, but personally I don't want to touch migrations to fix our previous errors anytime soon.

**Comment by chrismedrela** [comment]
Side note: squashing migrations doesn't speed up applying them. I've squashed first 87 migrations here (https://github.com/chrismedrela/amy/commit/4e5a29a02e877827397a50d44a630609cb40386b) and there is no improvement -- applying migrations still takes ~30 seconds on my machine.

**Comment by pbanaszkiewicz** [comment]
I don't think we have manpower to do the switch right now, so I'm postponing until I don't know when.

**Comment by gvwilson** [comment]
:+1:

**Comment by maneesha** [comment]
@pbanaszkiewicz  is this something that we still need to consider?

**Comment by pbanaszkiewicz** [comment]
@maneesha no, I don't feel like we need this transition anymore. Data migrations work just fine.
