### ISSUE TITLE
Check other ticketing systems if they're better than Eventbrite

### ISSUE THREAD

**Issue by apawlik** [carpentries/amy#628]
Is it possible to feed back the contact address as set in the index header back to Eventbrite for the particular event?
Currently the templates in Eventbrite have admin email as contact. People end up emailing our admins which is a problem. Manually setting the contact in Eventbrite (when setting up the event) is problematic for the admins. Ideally once the event is in AMY (and has Eventbrite connected with it), there would be a trigger updating the contact address in Eventbrite. Does Evebr API allow for that?
@pbanaszkiewicz ?

**Comment by pbanaszkiewicz** [comment]
@apawlik I don't see an option to set contact in here: https://www.eventbrite.com/developer/v3/endpoints/events/#ebapi-post-events-id

Eventbrite API is very limited and currently not much of a use for us. We can't even automate creating events (see #350).

**Comment by maneesha** [comment]
This is one of many frustrating things about Eventbrite.  
When you change the contact address the change actually happens globally, not just for that one event.  So you have to go back and change it for each event.  For example, if you change it to someone at UConn for an event at UConn, and then you create an event for Harvard, if you don't remember to change it, then the UConn person will get emails for the Harvard event and any other event after that.  In a word, it sucks.

You can have another person get all the "Contact the Organizer" emails just for that one event  through "Multi User Access" in the Settings section.  From there you can also see all events for a user but not all users for an event.  Another huge gripe.

When I have some more time I want to look at other event ticketing systems that might have more options for customization.

**Comment by maneesha** [comment]
Following up on my point above about Multi User Access, I usually let the host/organizer know they'll be included on all "Contact the Organizer" emails so they can respond accordingly.  It still means I (admin@swc) but at least I don't have to directly respond.

**Comment by pbanaszkiewicz** [comment]
Okay, let this be a research task for @maneesha for January: to look for other event ticketing systems.

**Comment by gvwilson** [comment]
Can this one now be closed?

**Comment by tracykteal** [comment]
I'd still like to pursue this.  I'm not sure this should be an AMY issue though except for understanding the API integration. Thoughts on the ti.to API? https://ti.to/docs/integrations

**Comment by pbanaszkiewicz** [comment]
When it comes to API, Tito seems similar to Eventbrite, for example list of event parameters is quite short: http://teamtito.github.io/tito-api-docs/#attributes29

**Comment by maneesha** [comment]
I've explored Tito, Ticketleap, and several other registration systems and haven't found anything that meets our needs better.  Closing this.
