### ISSUE TITLE
Need a way to record host site in event

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#727]
Online instructor training events frequently have participants from multiple sites. When we list someone as a 'host' for such an event, it would be helpful if we could list the site at which they're hosting.

**Comment by pbanaszkiewicz** [comment]
@gvwilson and 'site' in this context means…?

**Comment by gvwilson** [comment]
For example, in https://amy.software-carpentry.org/workshops/event/2016-06-08-ttt-online, I'd like to be able to record the three participating sites as a first-class database relationship, not as text in the comments field.

**Comment by pbanaszkiewicz** [comment]
@gvwilson so you want to have a M2M relationship between `Event` and `Host`, correct?

**Comment by gvwilson** [comment]
"Want" may be too strong a term - I certainly don't want to complicate 
the normal many-to-one relationship, but yeah, for instructor training...

**Comment by maneesha** [comment]
Something similar may come up in standard workshops too, where two universities are jointly running a workshop.  It may be physically located at University A but University B is equally involved.  This is rare but possible.

**Comment by gvwilson** [comment]
Good point.

**Comment by maneesha** [comment]
This is addressed through our new system that allows multiple member sites to be attached to a single instructor training event.  Closing this.
