### ISSUE TITLE
Generate randomized links to sign up for instructor training from partner sites

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#877]
If we're doing instructor training for a partner site, they'll send us names and email addresses of participants. We should send those people a randomized link to the instructor training application page so that:
1.  We can automatically identify which event they're part of.
2.  We can change the wording in the header to make it clear that they're guaranteed a spot in a particular event.

**Comment by pbanaszkiewicz** [comment]
Is this scheduled for v1.6.3 or later?

**Comment by gvwilson** [comment]
Later.

**Comment by pbanaszkiewicz** [comment]
Should this be included in v1.7 (in next 4 days) or later?

**Comment by gvwilson** [comment]
This one does not need to be in v1.7, but should be in v1.8.

**Comment by maneesha** [comment]
Closing this as we have systems for member sites to sign up for events with a code on Eventbrite.
