### ISSUE TITLE
Generate links for initially filled-in training request form

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#914]
1. When accessing `https://amy.software-carpentry.org/workshops/request_training/?group=antarctica-2016`, the "group" field should be filled in with `antarctica-2016`.
2. Admins should be able to enter a list of email addresses and bulk send email with this link.

**Comment by maneesha** [comment]
@karenword @sheraaronhurt 
Would you find this useful?  It may help for links we share with our member sites.  However I'd also be worried about people sharing the links externally, and end up prepopulating the field even though it's not their code.

As with all the others please rate on this scale:

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by karenword** [comment]
I think this is really more of an admin issue, so I'll defer. On the training end I don't see much benefit except in the case of in-person events — online events will need the registration code for Eventbrite anyway (unless that can be changed), so only in-person trainees & communications will get out of having to use/distribute the registration code by auto-filling it here.

**Comment by sheraaronhurt** [comment]
@maneesha @karenword  I would say a #4. This is something that isn't really relevant right now but the use of group/registration codes do need to be discussed as it relates to the IT application form.

**Comment by maneesha** [comment]
Closing this as we are not using this feature.
