### ISSUE TITLE
Email templates in trainees list view

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#923]
#871 introduces trainees list view with "email selected trainees" feature, which create an empty email.

It'd be useful to have three kinds of emails:
- empty email
- asking for confirmation of interest in training (aimed at trainees who have sent a request in past and are now part of group application sent by a partner)
- asking for filling training request form (aimed at trainees  who have not sent a request yet and are part of group application sent by a partner)

This can be implemented as a button:

![image](https://cloud.githubusercontent.com/assets/1645996/17186762/d2f0e08e-5436-11e6-97ff-c4a7027ebf1a.png)

When you click the button, an empty email is created. When you click the arrow on the right side, more options are available:
![image](https://cloud.githubusercontent.com/assets/1645996/17186787/e9a0891a-5436-11e6-9b2f-2c0f843ebe04.png)

**Comment by gvwilson** [comment]
:+1:

**Comment by pbanaszkiewicz** [comment]
@maneesha @sheraaron do you want this feature implemented? It's quite easy to do.

**Comment by sheraaron** [comment]
@pbanaszkiewicz  this would be amazing! I have to email persons to remind them to complete checkout requirements! So being able to do this and not copy each email would save me AT LEAST 15-30 min!

**Comment by pbanaszkiewicz** [comment]
@sheraaron please provide me with the email contents and I'll implement this feature.

**Comment by sheraaron** [comment]
@pbanaszkiewicz  [here](https://docs.carpentries.org/topic_folders/instructor_training/email_templates_admin.html#checkout-deadline-approaching) is the verbiage for "Checkout deadline approaching". Thanks!!!

**Comment by jduckles** [comment]
I don't want to stop progress on this, but please note for the future that @fmichonneau has a proposal to change how the text @sheraaron linked to is represented. This would create an opportunity for AMY to treat the template emails in [carpentries/hadnbook](https://github.com/carpentries/handbook) as THE source of truth to sync from.  

@pbanaszkiewicz Your thoughts on  https://github.com/carpentries/handbook/pull/232 would be good to have as you go about implementing this.  I think at a minimum we should define the template language/syntax we're using, and some dictionary of variable names we agree to use in templates (`{name} == amy.personal`, `{fullname} == amy.personal + amy.family` etc.).

**Comment by maneesha** [comment]
@sheraaronhurt @Talishask  Are you using any of the "mail selected participants" feature in AMY? If so we can revisit this more now; if not we can save it for an upcoming project if we look at email automations again.

**Comment by Talishask** [comment]
I haven't used it. I am not sure how it works but would love to revisit this with our email automations.

**Comment by sheraaronhurt** [comment]
@maneesha  I am not using it. I would like to discuss this to ensure I understand. If these are people in AMY, then they already have an application on file. Want to make sure it is worth having and it will be used before implementing

**Comment by maneesha** [comment]
Closing this here as this is being discussed in the email automations project.
