### ISSUE TITLE
Social auth links management page

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#930]
Implement a page available for everyone helping manage their social auth links, ie. logins from other sites than GitHub.

Ref #893.

**Comment by chrismedrela** [comment]
I think it'd be better if v1.8 release was solely for instructor training functionalities.

**Comment by pbanaszkiewicz** [comment]
This wouldn't be the first time something was proposed for specific release but got delayed.

**Comment by maneesha** [comment]
We are just using GitHub authentication for now and have not come across any problems with this, so I am closing it.  We can re-open if we consider other ways of enabling login.
