### ISSUE TITLE
Allow admins to add/change messages on forms

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#947]
The workshop request form, instructor training request form, and others should each be able to display an optional message, the content of which should be set by the admin.  Simplest implementation I can think of is:
-   A new "messages" table with a short text key and a large text message field that may contain HTML.
-   A single page that allows the admins to edit the messages associated with various keys (all displayed on one page).
-   A conditional in each form that displays its message if there is one.

We do _not_ need to add the ability to create new records in the messages table - that can be done by a migration when new forms are added.

**Comment by chrismedrela** [comment]
I thought that there is already Django app to do this, but I cannot google it.

**Comment by pbanaszkiewicz** [comment]
Maybe slightly related: https://docs.djangoproject.com/en/1.9/ref/contrib/flatpages/

Eventually I'd want to go a step further: allow admins to completely modify the forms (like Google forms), but that's only an idea…

**Comment by chrismedrela** [comment]
I don't think that we can fix this issue with `flatpages`, but thanks for pointing it out.

> Eventually I'd want to go a step further: allow admins to completely modify the forms (like Google forms), but that's only an idea…

Hmmm, that requires a lot of work unless you're considering some specific subset of Google Forms features.

**Comment by maneesha** [comment]
If we want the forms to connect with the database models I don't think that should be something admins  can easily change.

**Comment by pbanaszkiewicz** [comment]
@maneesha would this be useful for you? Not so hard to implement for forms.

**Comment by maneesha** [comment]
Closing as I don't think anyone is using email messages.
