### ISSUE TITLE
Find whether people have had a task at a workshop together

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#962]
I'd like to input 2 (or more) people and return what workshops (if any) those people have had a role in (any role). 

Low priority but it would help me when I place people at workshops to know if they've worked together before.

**Comment by pbanaszkiewicz** [comment]
@maneesha  This is mostly intended for finding staff, not participants, right?

**Comment by maneesha** [comment]
Yes - this should apply to instructor, host, helper, and organizer.
Does not apply to learner.

**Comment by maneesha** [comment]
Closing this as stale/not a priority.
