### ISSUE TITLE
Needed: data consistency problem display for training

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#972]
I would like a display that shows me people who have a SWC instructor badge, but don't have all the prerequisite steps recorded.  Ditto for DC.  And a way to mark certain people as "yes, we know about the problem in our records, but we're not worried about."

**Comment by chrismedrela** [comment]
> I would like a display that shows me people who have a SWC instructor badge, but don't have all the prerequisite steps recorded.

So far, we use the following convention in "eligible?" column in trainees view:

![image](https://cloud.githubusercontent.com/assets/1645996/18028437/9a1d34cc-6c7f-11e6-86ef-ef59e393a36a.png)

We can add the following label:
![image](https://cloud.githubusercontent.com/assets/1645996/18028432/7129404c-6c7f-11e6-9b7c-31123c0164fa.png)

We can also add two checkboxes in filter box to filter out people who have yellow SWC or DC label, but the queryset won't be trivial.

> And a way to mark certain people as "yes, we know about the problem in our records, but we're not worried about."

The easiest way is probably to add `BooleanField` to `Award`.

**Comment by gvwilson** [comment]
I like the orange for "certified but missing some requirements". If you 
can add a "sort by certification date" option to the trainees display, 
that would (mostly) eliminate the need for a "yes we know about the 
problem" field.  (It should probably be "sort by most recent 
certification" for people who have both.)

**Comment by maneesha** [comment]
Closing this - This is addressed by this new view:

![image](https://user-images.githubusercontent.com/829690/60040335-b7815000-9686-11e9-8f02-43e1d2e55e7c.png)
