### ISSUE TITLE
Pulldown for "evaluated by" in training records should show everyone

### ISSUE THREAD

**Issue by gvwilson** [carpentries/amy#982]
Right now the pulldown for "evaluated by" only shows a few people (and I can't figure out why those ones and not others). It should auto-complete with everyone, since there may be many different people running discussion sessions.

**Comment by chrismedrela** [comment]
@maneesha right now we display only people belonging to "administrators" group. Should we display people belonging to "administrators" or "trainers" group? Or also "steering committee" and "invoicing"?

**Comment by maneesha** [comment]
We can leave as is for now.  See #1287 where we will be revisiting who has what level of access across the AMY system.
