### ISSUE TITLE
Add editable DateField to TrainingProgress

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#983]
Similar to `Badge.awarded_at`.

**Comment by maneesha** [comment]
@pbanaszkiewicz  Is this still relevant given all the changes we've made to tracking instructor training progress?

**Comment by pbanaszkiewicz** [comment]
@maneesha we still don't have such field on `TrainingProgress`. Currently we only have two fields that store creation timestamp and last update timestamp. This new field would indicate when specific training progress item was awarded / given, and this can be a different date than creation timestamp. So this is question to people handling awarding training progresses - do they want this additional information stored with training progress?

**Comment by maneesha** [comment]
Thanks @pbanaszkiewicz  for clarifying. 

I'll leave this to @ErinBecker  and @karenword  to assess.

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by karenword** [comment]
Also deferring on this to @ErinBecker as a checkout item

**Comment by ErinBecker** [comment]
5. No longer relevant - OK to close
