### ISSUE TITLE
UI Improvements to the bulk import workflow

### ISSUE THREAD

**Issue by aditnryn** [carpentries/amy#986]
- In the bulk import workflow, we can hide the instances that have been marked NOT to be imported to free up screen space and it also makes it easier to locate the errors that occur during the import process in consequent submissions.
- Allow administrators to easily switch between importing instances of speakers, presentations and sponsorships.

**Comment by maneesha** [comment]
@sheraaronhurt  As far as I've seen I don't think we need to make changes to the "Bulk import person" feature.  Let me know if you want to address anything here.


**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by pbanaszkiewicz** [comment]
This issue is specific for PyData component.
