### ISSUE TITLE
Prevent garbage speaker profiles from being automatically imported

### ISSUE THREAD

**Issue by aditnryn** [carpentries/amy#992]
Conference sites do have speaker profiles with empty name and email address fields. The bulk import workflow end up importing these garbage profiles into AMY.
AMY needs a validation check to filter out these profiles.

**Comment by pbanaszkiewicz** [comment]
Dropping PyData bugs/features from AMY for now.

**Comment by maneesha** [comment]
Closing this since it seems to be just about PyData.
